### ISSUE TITLE
Selection script causes Scheduler Server to crash

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/scheduling#2257]
I submitted a selection script 'sleep infinity', to see what happens when someone does a mistake in the selection scripts. It became a fork bomb and caused the server to crash.

I submitted the following job:

```xml 
<?xml version="1.0" encoding="UTF-8"?>
<job
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:proactive:jobdescriptor:3.2"
     xsi:schemaLocation="urn:proactive:jobdescriptor:3.2 http://www.activeeon.com/public_content/schemas/proactive/jobdescriptor/3.2/schedulerjob.xsd"
    name="Examples Selection script" 
    priority="normal"
    cancelJobOnError="false">
  <variables>
    <variable name="NUMBER_OF_PING" value="4"/>
  </variables>
  <description>
    <![CDATA[ Here a native command will be executed, with an argument.
        We also define a variable above and use it a parameter. ]]>
  </description>
  <taskFlow>
    <task name="Bash_Task">
      <description>
        <![CDATA[ The simplest task, ran by a bash engine. ]]>
      </description>
      <selection>
        <script type="dynamic" >
          <code language="bash">
            <![CDATA[
sleep infinity
]]>
          </code>
        </script>
      </selection>
      <scriptExecutable>
        <script>
          <code language="bash">
            <![CDATA[
docker ps
]]>
          </code>
        </script>
      </scriptExecutable>
      <controlFlow block="none"></controlFlow>
    </task>
  </taskFlow>
</job>```



Here are the logs

================= Job 586 logs =================
[2015-07-01 14:50:25,107 INFO             o.o.p.s.u.JobLogger] job 586 submitted: name 'Examples Selection script', tasks '1', owner 'pa0427'
[2015-07-01 14:50:25,108 INFO             o.o.p.s.u.JobLogger] job 586 Job 'Examples Selection script' : 
    Environment = null
    Description = 'Here a native command will be executed, with an argument.
        We also define a variable above and use it a parameter.'
    ProjectName = 'Not Assigned'
    Priority = Normal
    InputSpace = 'null'
    OutputSpace = 'null'
    GlobalSpace = 'null'
    UserSpace = 'null'
    Variables = {NUMBER_OF_PING=4}
    Tasks = {
Task 'Bash_Task' : 
    FlowBlock = 'none'
    Description = 'The simplest task, ran by a bash engine.'
    ResultPreview = 'null'
    InputFiles = null
    OutputFiles = null
    ParallelEnvironment = null
    SelectionScripts = {  { 
Script 'SimpleScript'
    scriptEngineLookup = 'bash'
    script = 
sleep infinity
    id = 
sleep infinity
    parameters = null
} }
    PreScript = null
    PostScript = null
    CleanScript = null
    FlowScript = null
    PreciousResult = false
    PreciousLogs = false
    RunAsMe = false
    WallTime = 0
    Dependences = null
    ExecutableClassName = 'org.ow2.proactive.scheduler.task.forked.JavaForkerExecutable'
    Arguments = []

    ForkEnvironment = 'null
    Script =  { 
Script 'SimpleScript'
    scriptEngineLookup = 'bash'
    script = 
docker ps
    id = 
docker ps
    parameters = null
}

}
[2015-07-02 15:13:33,623 INFO             o.o.p.s.u.JobLogger] job 586 ending request
[2015-07-02 15:13:33,638 INFO             o.o.p.s.u.JobLogger] job 586 finished (Killed)
[2015-07-02 15:13:33,638 INFO             o.o.p.s.u.JobLogger] job 586 cleaning loggers
[2015-07-02 15:13:33,638 INFO             o.o.p.s.u.JobLogger] job 586 removing TaskClassServer

================ Task 5860000 logs =================
[2015-07-02 07:37:17,087 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 0 nodes 
[2015-07-02 07:39:01,087 INFO            o.o.p.s.u.TaskLogger] task 5860000 scheduling
[2015-07-02 07:39:01,105 INFO      o.o.p.r.s.SelectionManager] "scheduler" requested 1 nodes with ArbitraryTopologyDescriptor
[2015-07-02 07:39:01,160 INFO        o.o.p.r.s.ScriptExecutor] pamr://4098/SSH-local-0 : -1665135755 executing
[2015-07-02 07:39:01,168 INFO        o.o.p.r.s.ScriptExecutor] pamr://4100/SSH-local-2 : -1665135755 executing
[2015-07-02 07:39:01,168 INFO        o.o.p.r.s.ScriptExecutor] pamr://4097/SSH-local-1 : -1665135755 executing
[2015-07-02 07:39:01,168 INFO        o.o.p.r.s.ScriptExecutor] pamr://4099/SSH-local-3 : -1665135755 executing
[2015-07-02 07:39:03,390 WARN        o.o.p.r.s.ScriptExecutor] pamr://4099/SSH-local-3 : exception during the script execution
java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor361.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

    at org.ow2.proactive.scripting.Script.execute(Script.java:341)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor361.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
[2015-07-02 07:39:06,308 WARN        o.o.p.r.s.ScriptExecutor] pamr://4098/SSH-local-0 : exception during the script execution
java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

    at org.ow2.proactive.scripting.Script.execute(Script.java:341)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
[2015-07-02 07:39:09,386 WARN        o.o.p.r.s.ScriptExecutor] pamr://4100/SSH-local-2 : exception during the script execution
java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

    at org.ow2.proactive.scripting.Script.execute(Script.java:341)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
[2015-07-02 07:39:31,201 WARN      o.o.p.r.s.SelectionManager] Ignoring exception in selection script: org.ow2.proactive.scripting.ScriptException: java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

[2015-07-02 07:39:31,217 WARN      o.o.p.r.s.SelectionManager] Ignoring exception in selection script: org.ow2.proactive.scripting.ScriptException: java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

[2015-07-02 07:39:31,217 WARN      o.o.p.r.s.SelectionManager] Timeout on script execution on the node pamr://4097/SSH-local-1 using the following scripts
sleep infinity

[2015-07-02 07:39:31,217 WARN      o.o.p.r.s.SelectionManager] Ignoring exception in selection script: org.ow2.proactive.scripting.ScriptException: java.lang.Exception: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:73)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:48)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:38)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:16)
    at jsr223.nativeshell.NativeShellScriptEngine.eval(NativeShellScriptEngine.java:21)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:324)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
    at sun.reflect.GeneratedMethodAccessor361.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "bash": error=24, Trop de fichiers ouverts
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at jsr223.nativeshell.NativeShellRunner.run(NativeShellRunner.java:60)
    ... 22 more
Caused by: java.io.IOException: error=24, Trop de fichiers ouverts
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 23 more

[2015-07-02 07:39:31,217 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 0 nodes 
[2015-07-02 15:13:01,797 INFO            o.o.p.s.u.TaskLogger] task 5860000 scheduling
[2015-07-02 15:13:01,801 INFO      o.o.p.r.s.SelectionManager] "scheduler" requested 1 nodes with ArbitraryTopologyDescriptor
[2015-07-02 15:13:01,811 INFO        o.o.p.r.s.ScriptExecutor] pamr://4098/SSH-local-1 : -1665135755 executing
[2015-07-02 15:13:01,812 INFO        o.o.p.r.s.ScriptExecutor] pamr://4100/SSH-local-0 : -1665135755 executing
[2015-07-02 15:13:01,814 INFO        o.o.p.r.s.ScriptExecutor] pamr://4097/SSH-local-3 : -1665135755 executing
[2015-07-02 15:13:01,815 INFO        o.o.p.r.s.ScriptExecutor] pamr://4099/SSH-local-2 : -1665135755 executing
[2015-07-02 15:13:31,811 WARN      o.o.p.r.s.SelectionManager] Timeout on script execution on the node pamr://4098/SSH-local-1 using the following scripts
sleep infinity

[2015-07-02 15:13:31,811 WARN      o.o.p.r.s.SelectionManager] Timeout on script execution on the node pamr://4100/SSH-local-0 using the following scripts
sleep infinity

[2015-07-02 15:13:31,812 WARN      o.o.p.r.s.SelectionManager] Timeout on script execution on the node pamr://4097/SSH-local-3 using the following scripts
sleep infinity

[2015-07-02 15:13:31,812 WARN      o.o.p.r.s.SelectionManager] Timeout on script execution on the node pamr://4099/SSH-local-2 using the following scripts
sleep infinity

[2015-07-02 15:13:31,812 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 0 nodes

**Comment by youribonnaffe** [comment]
What probably happened is that the selection scripts were timing out (on the server side), and then re-executed in the next scheduling loop iteration since no nodes were selected. In the end many sleep commands were executed, probably exhausting the allowed number of open files.

There is a feature in the Scheduler to only allow scripts from a specific folder (i.e scripts edited by an administrator).

**Comment by tobwiens** [comment]
Is that the wanted behavior, that selection scripts are never killed? Why do they time out?

I think that selection script or all type of scripts should be killed after they time out.

**Comment by fviale** [comment]
We could eventually run a ProcessTreeKiller to make sure the selection
script didn't spawn unwanted processes.

**Comment by youribonnaffe** [comment]
As the script engine API does not provide a stop method, we won't have any way to prevent a script like _for(;;)_ to run forever

**Comment by fviale** [comment]
That's not false.

**Comment by tobwiens** [comment]
I found something on stackoverflow about it:
http://stackoverflow.com/questions/1601246/java-scripting-api-how-to-stop-the-evaluation

It seems that there is no proper way to stop script engines. 

Script engines are used for tasks, how are those killed then?

**Comment by youribonnaffe** [comment]
That is why forking is a good idea :). There you can kill the process itself.
Otherwise you can always try to interrupt the thread, it might work for calls like Thread.sleep but won't for infinite loops like _for(;;)_

**Comment by tobwiens** [comment]
More like a necessity!

Can we execute the selection scripts inside a forked JVM and then kill the thread after some time, like we're doing it with tasks? Is there any differentiation from executing a selection script or a normal task?

**Comment by youribonnaffe** [comment]
Then selection scripts would be even more costly (they might be executed frequently until a matching node is found, and probably several time per host given there are multiple nodes on the same host).

Selection is executed on the node (from the modules point of view, rm-node), tasks inside a task launcher (scheduler-node) with much things like bindings, dataspaces,...

**Comment by tobwiens** [comment]
Costly versus being able to break a whole cluster through an unprivileged user's mistake or intention.

How much is the overhead of forking a JVM?

**Comment by bamedro** [comment]
Selection scripts are often used as dynamic instead of static. If static, they are not that costly.
Forking a jvm is something like 200ms if I remember correctly.

**Comment by tobwiens** [comment]
I think we should secure them by running them inside a forked JVM, because if someone does a mistake the mistake will run forever on all nodes. 
Maybe we can add as a note that it is resource intensive and should be used sparsely.

**Comment by fviale** [comment]
A lot of selection scripts test if java properties are set on a given Node
(tokens).

We cannot run them on forked Node as it will break their usage and make
them pointless in most cases.

**Comment by fviale** [comment]
We cannot cancel infinite loops, but we can cancel operations that are
"interruptable" (which can be inside an infinite loop).
