### ISSUE TITLE
Cannot add a node from the interactive client

### ISSUE THREAD

**Issue by sandrineBeauche** [ow2-proactive/scheduling#2291]
Got this error when trying to add a node from the interactive client:

An error occurred while adding the node:
HTTP Error Code: 500
Error Message: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrin
oun:5321/local-localNodes-5
Stack Trace:
org.ow2.proactive.resourcemanager.exception.AddingNodesException: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeExcep
tion: Cannot get the node based on pnp://pc-sandrinoun:5321/local-localNodes-5
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(NodeSource.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:192)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.runActivity(NodeSource.java:234)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        at java.lang.Thread.run(Thread.java:722)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourcemanage
r.nodesource.NodeSource_-b11cdd-14f23298f1e--7f34--6170c644dedc7401--b11cdd-14f23298f1e--8000)
        at (...)(Unknown Source)
        at org.ow2.proactive.resourcemanager.frontend.ResourceManager.addNode([pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourcemanage
r.core.RMCore_-b11cdd-14f23298f1e--7ffc--6170c644dedc7401--b11cdd-14f23298f1e--8000, pnp://pc-sandrinoun:64738/RMCORE])
        at (...)(Unknown Source)
        at org.ow2.proactive.resourcemanager.common.util.RMProxyUserInterface.addNode(pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourc
emanager.common.util.RMProxyUserInterface_-b11cdd-14f23298f1e--7faa--6170c644dedc7401--b11cdd-14f23298f1e--8000)
        at (...)(Unknown Source)
        at org.objectweb.proactive.api.PAFuture.getFutureValue(PAFuture.java:118)
        at org.objectweb.proactive.api.PAFuture.getFutureValue(PAFuture.java:82)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:349)
        at org.objectweb.proactive.core.body.future.FutureProxy.reify(FutureProxy.java:460)
        at pa.stub.org.objectweb.proactive.core.util.wrapper._StubBooleanWrapper.getBooleanValue(_StubBooleanWrapper.java)
        at org.ow2.proactive_grid_cloud_portal.rm.RMRest.addNode(RMRest.java:289)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrinoun:
5321/local-localNodes-5
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:262)
        at java.util.concurrent.FutureTask.get(FutureTask.java:119)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.lookupNode(NodeSource.java:433)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(NodeSource.java:288)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:192)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.runActivity(NodeSource.java:234)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        ... 1 more
Caused by: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrinoun:5321/local-localNodes-5
        at org.objectweb.proactive.core.node.NodeFactory.getNode(NodeFactory.java:271)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource$NodeLocator.call(NodeSource.java:418)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource$NodeLocator.call(NodeSource.java:410)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        ... 1 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPException: Lookup of pnp://pc-sandrinoun:5321/local-localNodes-5failed due to network e
rror
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryBackend.lookup(PNPRemoteObjectFactoryBackend.java:182)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryAbstract.lookup(PNPRemoteObjectFactoryAbstract.java:116)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectHelper.lookup(RemoteObjectHelper.java:166)
        at org.objectweb.proactive.core.runtime.RuntimeFactory.getRuntime(RuntimeFactory.java:203)
        at org.objectweb.proactive.core.node.NodeFactory.getNode(NodeFactory.java:269)
        ... 7 more
Caused by: org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://pc-sandrinoun:5321/local-localNodes-5
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:117)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryBackend.lookup(PNPRemoteObjectFactoryBackend.java:174)
        ... 11 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPIOException: Failed to connect to pc-sandrinoun/192.168.1.43:5321
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannel.<init>(PNPAgent.java:377)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:317)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:305)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:187)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:175)
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:115)
        ... 12 more
Caused by: java.net.ConnectException: Connection refused: no further information: pc-sandrinoun/192.168.1.43:5321
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        ... 3 more

**Comment by sandrineBeauche** [comment]
Got the same error in the non-interactive mode:

```
PS C:\data\sandbox\scheduling-6.3.0-SNAPSHOT\bin> .\proactive-client.bat -X -a pnp://pc-sandrinoun:7314/local-LocalNodes-8
An error occurred while adding the node:
HTTP Error Code: 500
Error Message: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrin
oun:7314/local-LocalNodes-8
Stack Trace:
org.ow2.proactive.resourcemanager.exception.AddingNodesException: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeExcep
tion: Cannot get the node based on pnp://pc-sandrinoun:7314/local-LocalNodes-8
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(NodeSource.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:192)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.runActivity(NodeSource.java:234)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        at java.lang.Thread.run(Thread.java:722)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourcemanage
r.nodesource.NodeSource_61018204-14f25e09ac1--7b67--6170c644dedc7401-61018204-14f25e09ac1--8000)
        at (...)(Unknown Source)
        at org.ow2.proactive.resourcemanager.frontend.ResourceManager.addNode([pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourcemanage
r.core.RMCore_61018204-14f25e09ac1--7ff7--6170c644dedc7401-61018204-14f25e09ac1--8000, pnp://pc-sandrinoun:64738/RMCORE])
        at (...)(Unknown Source)
        at org.ow2.proactive.resourcemanager.common.util.RMProxyUserInterface.addNode(pnp://pc-sandrinoun:64738/ActiveObject_org.ow2.proactive.resourc
emanager.common.util.RMProxyUserInterface_61018204-14f25e09ac1--7d12--6170c644dedc7401-61018204-14f25e09ac1--8000)
        at (...)(Unknown Source)
        at org.objectweb.proactive.api.PAFuture.getFutureValue(PAFuture.java:118)
        at org.objectweb.proactive.api.PAFuture.getFutureValue(PAFuture.java:82)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:349)
        at org.objectweb.proactive.core.body.future.FutureProxy.reify(FutureProxy.java:460)
        at pa.stub.org.objectweb.proactive.core.util.wrapper._StubBooleanWrapper.getBooleanValue(_StubBooleanWrapper.java)
        at org.ow2.proactive_grid_cloud_portal.rm.RMRest.addNode(RMRest.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrinoun:
7314/local-LocalNodes-8
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:262)
        at java.util.concurrent.FutureTask.get(FutureTask.java:119)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.lookupNode(NodeSource.java:433)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(NodeSource.java:288)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:192)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource.runActivity(NodeSource.java:234)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        ... 1 more
Caused by: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrinoun:7314/local-LocalNodes-8
        at org.objectweb.proactive.core.node.NodeFactory.getNode(NodeFactory.java:271)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource$NodeLocator.call(NodeSource.java:418)
        at org.ow2.proactive.resourcemanager.nodesource.NodeSource$NodeLocator.call(NodeSource.java:410)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        ... 1 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPException: Lookup of pnp://pc-sandrinoun:7314/local-LocalNodes-8failed due to network e
rror
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryBackend.lookup(PNPRemoteObjectFactoryBackend.java:182)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryAbstract.lookup(PNPRemoteObjectFactoryAbstract.java:116)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectHelper.lookup(RemoteObjectHelper.java:166)
        at org.objectweb.proactive.core.runtime.RuntimeFactory.getRuntime(RuntimeFactory.java:203)
        at org.objectweb.proactive.core.node.NodeFactory.getNode(NodeFactory.java:269)
        ... 7 more
Caused by: org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://pc-sandrinoun:7314/local-LocalNodes-8
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:117)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObjectFactoryBackend.lookup(PNPRemoteObjectFactoryBackend.java:174)
        ... 11 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPIOException: Failed to connect to pc-sandrinoun/192.168.1.43:7314
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannel.<init>(PNPAgent.java:377)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:317)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:305)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:187)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:175)
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:115)
        ... 12 more
Caused by: java.net.ConnectException: Connection refused: no further information: pc-sandrinoun/192.168.1.43:7314
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        ... 3 more
```

**Comment by sandrineBeauche** [comment]
I started in a new shell, proactive-node.bat and obtained a new node with this address:  pnp://pc-sandrinoun:14028/pc-sandrinoun_2868. This node has been automatically added to the ressource manager. So I removed it by using the web portal and tried the command .\proactive-client.bat -X -a pnp://pc-sandrinoun:14028/pc-sandrinoun_2868 and it does not work:

```
An error occurred while adding the node:
HTTP Error Code: 500
Error Message: java.util.concurrent.ExecutionException: org.objectweb.proactive.core.node.NodeException: Cannot get the node based on pnp://pc-sandrin
oun:14028/pc-sandrinoun_2868
```
