### ISSUE TITLE
RunAsMe feature does not work on Windows 8

### ISSUE THREAD

**Issue by sandrineBeauche** [ow2-proactive/scheduling#2295]
On windows 8, I logged with my account Sandrine, and configured a Proactive agent following the [RunAsMe WITHOUT Active Directory instructions](https://docs.google.com/document/d/1GDkVMvwxpLm2w8uui7FpF5c8IviDL2JCiATVp3kBs-g/edit).

Then I logged to the scheduler with the runasme account, and launch workflows. They seems to work correctly. But I launched a workflow with a native windows task that echoes the current username.
Here the workflow:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<job
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:proactive:jobdescriptor:3.2"
     xsi:schemaLocation="urn:proactive:jobdescriptor:3.2 http://www.activeeon.com/public_content/schemas/proactive/jobdescriptor/3.2/schedulerjob.xsd"
    name="echo_user2" 
    priority="normal"
    cancelJobOnError="false">
  <description>
    <![CDATA[ Here a native command will be executed, with an argument. ]]>
  </description>
  <taskFlow>
    <task name="Windows"




    runAsMe="true" >
      <nativeExecutable>
        <staticCommand value="cmd.exe" >
          <arguments>
            <argument value="/c"/>
            <argument value="echo %USERNAME%"/>
          </arguments>
        </staticCommand>
      </nativeExecutable>
      <controlFlow block="none"></controlFlow>
    </task>
  </taskFlow>
</job>
```

The expected output should be "runasme", but it is "proactive"

**Comment by sandrineBeauche** [comment]
Got this error on Windows 7, when running the dataspace sample in runAsMe mode:

```
java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;
    at com.sun.jna.Structure.fieldOrder(Structure.java:884)
    at com.sun.jna.Structure.getFields(Structure.java:910)
    at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
    at com.sun.jna.Structure.calculateSize(Structure.java:982)
    at com.sun.jna.Structure.calculateSize(Structure.java:949)
    at com.sun.jna.Structure.allocateMemory(Structure.java:375)
    at com.sun.jna.Structure.<init>(Structure.java:184)
    at com.sun.jna.Structure.<init>(Structure.java:172)
    at com.sun.jna.Structure.<init>(Structure.java:159)
    at com.sun.jna.Structure.<init>(Structure.java:151)
    at com.sun.jna.platform.win32.WinBase$SECURITY_ATTRIBUTES.<init>(WinBase.java:568)
    at org.objectweb.proactive.extensions.processbuilder.WindowsProcess.startWithLogon(WindowsProcess.java:495)
    at org.objectweb.proactive.extensions.processbuilder.WindowsProcess.internalGetUserEnv(WindowsProcess.java:613)
    at org.objectweb.proactive.extensions.processbuilder.WindowsProcess.start(WindowsProcess.java:341)
    at org.objectweb.proactive.extensions.processbuilder.WindowsProcessBuilder.setupAndStart(WindowsProcessBuilder.java:233)
    at org.objectweb.proactive.extensions.processbuilder.WindowsProcessBuilder.start(WindowsProcessBuilder.java:102)
    at org.ow2.proactive.scheduler.task.forked.JavaForkerExecutable.startProcess(JavaForkerExecutable.java:753)
    at org.ow2.proactive.scheduler.task.forked.JavaForkerExecutable.execute(JavaForkerExecutable.java:188)
    at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1798)
    at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1793)
    at org.ow2.proactive.scheduler.task.utils.ActiveObjectExecutor.call(ActiveObjectExecutor.java:102)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:336)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by lpellegr** [comment]
@sandrineBeauche What is the version used for Java and JNA (you can find the version for JNA in _dist/lib/jna-*_)? If I remember correctly, [JNA has been upgraded](https://github.com/lpellegr/scheduling/commit/f82f422dd2f0c238b9fdadb91375e517cc44a047) at end of May since we had a similar issue.

**Comment by fviale** [comment]
Managed to make it work on windows 7 by doing the following steps :

1) Add to the node (enclosing) user (an admin) the following rights in Local Security Strategy :
Allow log locally
Adjust memory quotas for process
Replace process level token
2) Add to the runasme user the following rights :
Allow log locally
3) make the runasme account an admin
4) Add full control to the temp dir of the enclosing user (maybe unneccessary because of 3)
5) Add full control to the proactive installation directory (maybe unneccessary because of 3)
6) Reboot the machine

If the runasme account is not an admin, the following error occurs, even though I opened full control for all users (or for the specific runasme user)  on the proactive installation folder hierarchy :
```
org.ow2.proactive.scheduler.exception.StartForkedProcessException: Unable to create a separate java process. Exit code: -1073741502.
Process information:
Command:
H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\jre\bin\java -Djava.security.policy=H:\Users\fviale\AppData\Local\Temp\forked_jts6911963269626318927.tmp -Dpa.logs.home=H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\ -Dpa.forker.node=local-LocalNodes-2 -Dlog4j.configuration=file:H:\Users\fviale\AppData\Local\Temp\forked_jtl7994224801083309120.tmp -Dproactive.configuration=file:H:\Users\fviale\AppData\Local\Temp\forked_jtp4535724061093194116.properties -Dpas.launcher.logs.maxsize=0 -Dproactive.pamr.router.address=localhost -Dproactive.pamr.router.port=33647 -Dproactive.communication.amqp.broker.address=localhost -Dproactive.communication.amqp.broker.port=5672 -Dproactive.communication.amqp.broker.user=guest -Dproactive.communication.amqp.broker.password=guest -Dproactive.communication.amqp.broker.vhost=/ -Dproactive.communication.amqp_federation.broker.address=localhost -Dproactive.communication.amqp_federation.broker.port=5672 -Dproactive.communication.amqp_federation.broker.user=guest -Dproactive.communication.amqp_federation.broker.password=guest -Dproactive.communication.amqp_federation.broker.vhost=/ -cp .;.;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\addons;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\activation-1.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\amqp-client-3.0.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\antlr-2.7.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\apache-mime4j-0.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\args4j-2.0.16.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\async-http-client-1.8.14.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\atmosphere-runtime-2.2.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\bcprov-jdk15-136.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\c3p0-0.9.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\common-api-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\common-client-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-beanutils-1.8.3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-cli-1.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-codec-1.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-collections-3.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-httpclient-3.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-io-2.4.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-lang3-3.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-logging-1.1.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-net-2.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\commons-vfs2-2.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\cron4j-2.2.5.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\derby-10.8.2.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\dom4j-1.6.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\dozer-5.4.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\FastInfoset-1.2.12.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\groovy-all-2.1.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\guava-18.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\hibernate-c3p0-4.1.7.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\hibernate-commons-annotations-4.0.1.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\hibernate-core-4.1.7.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\hibernate-jpa-2.0-api-1.0.1.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\httpclient-4.2.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\httpcore-4.2.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\httpmime-4.2.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\isorelax-20030108.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\istack-commons-runtime-2.16.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackrabbit-jcr-commons-1.5.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackrabbit-webdav-1.5.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackson-core-asl-1.9.12.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackson-jaxrs-1.9.12.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackson-mapper-asl-1.9.12.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jackson-xc-1.9.12.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\javassist-3.12.1.GA.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\javassist-3.18.2-GA.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\javax.servlet-3.0.0.v201112011016.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\javax.servlet-api-3.0.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jaxb-api-2.2.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jaxb-core-2.2.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jaxb-impl-2.2.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jaxrs-api-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jboss-annotations-api_1.1_spec-1.0.1.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jboss-logging-3.1.0.GA.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jboss-transaction-api_1.1_spec-1.0.0.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jcip-annotations-1.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jcl-over-slf4j-1.6.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jdbm-2.0.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-continuation-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-http-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-io-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-security-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-server-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-servlet-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-util-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-webapp-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-websocket-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jetty-xml-8.1.15.v20140411.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jline-2.11.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jna-4.1.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jna-platform-4.1.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jruby-jline-1.7.4.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jsch-0.1.51.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jsr173_api-1.0.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jsr223-nativeshell-0.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\jython-jline-2.5.4-rc1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\log4j-1.2.17.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\mail-1.4.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\maven-scm-api-1.4.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\maven-scm-provider-svn-commons-1.4.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\maven-scm-provider-svnexe-1.4.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\msv-20050913.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\mysql-connector-java-5.1.16.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\netty-3.9.2.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\node-updater.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\plexus-utils-1.5.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\process-tree-killer-1.0.0-SNAPSHOT.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-annotation-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-core-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-amqp-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-annotation-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-dataspaces-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-pamr-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-pnp-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-pnpssl-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-processbuilder-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-rmissl-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-extension-vfsprovider-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\programming-util-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\regexp-1.3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\relaxngDatatype-20030807.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rest-api-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rest-cli-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rest-client-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rest-server-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rest-smartproxy-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\resteasy-client-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\resteasy-jackson-provider-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\resteasy-jaxb-provider-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\resteasy-jaxrs-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\resteasy-multipart-provider-3.0.6.Final.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rm-client-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rm-node-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rm-policy-scheduler-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rm-server-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\rrd4j-2.0.7.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scannotation-1.0.3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scheduler-api-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scheduler-client-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scheduler-node-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scheduler-server-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\scheduling-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\sigar-1.7.0-proactive.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\slf4j-api-1.7.5.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\slf4j-log4j12-1.6.6.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\smartproxy-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\smartproxy-common-6.3.0-RC3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\stax-api-1.0-2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\stax2-api-3.1.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\trilead-ssh2-build213-svnkit-1.3-patch.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\wasync-1.4.3.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\websockify-1.6-proactive.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\winp-1.23-proactive.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\woodstox-core-lgpl-4.1.2.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\xercesImpl-2.8.1.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\xml-apis-1.3.03.jar;H:\Users\fviale\Downloads\ProActiveWorkflowsScheduling-windows-x64-6.3.0-RC3\dist\lib\xsdlib-20050913.jar org.ow2.proactive.scheduler.task.forked.ForkerStarter pnp://precision.lan:49546/e0196692-4663-4269-b7c8-9736b3c17894 e0196692-4663-4269-b7c8-9736b3c17894
```

**Comment by fviale** [comment]
The RunAsMe issues on Windows seem difficult to fix, but it's a feature we sell and that we are unable to provide.

**Comment by fviale** [comment]
issue fixed by the following commits:

https://github.com/ow2-proactive/scheduling/commit/5de2d536ccdc1b3ec8531f2c3cd47a1f393ec5e2
https://github.com/ow2-proactive/programming/commit/31e988344b224ffe2f623b0230ebf6357a7cabaa

tests still need to be written
