### ISSUE TITLE
 java.lang.String cannot be cast to org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2297]
R script engine implementation is currently broken.

It seems to be caused by a change introduced with the Speed branch which was aiming to use a local absolute path instead of a VFS URL for local space.

Below is the stacktrace that is thrown when a simple R script is submitted for execution:

```
[30000@trydev.activeeon.com;10:24:17] Failed to execute task: java.lang.String cannot be cast to org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject 
[30000@trydev.activeeon.com;10:24:17] java.lang.ClassCastException: java.lang.String cannot be cast to org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.assignLocalSpace(PARScriptEngine.java:308) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:134) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:209) 
[30000@trydev.activeeon.com;10:24:17] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.Script.execute(Script.java:318) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:331) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:112) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.fromForkedJVM(ForkedTaskExecutor.java:316) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.main(ForkedTaskExecutor.java:309) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:334) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:112) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.fromForkedJVM(ForkedTaskExecutor.java:316) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.main(ForkedTaskExecutor.java:309) 
[30000@trydev.activeeon.com;10:24:17] Caused by: java.lang.Exception: java.lang.String cannot be cast to org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject 
[30000@trydev.activeeon.com;10:24:17] java.lang.ClassCastException: java.lang.String cannot be cast to org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.assignLocalSpace(PARScriptEngine.java:308) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:134) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:209) 
[30000@trydev.activeeon.com;10:24:17] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.Script.execute(Script.java:318) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:331) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:112) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.fromForkedJVM(ForkedTaskExecutor.java:316) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.main(ForkedTaskExecutor.java:309) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.Script.execute(Script.java:338) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[30000@trydev.activeeon.com;10:24:17] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:331) 
[30000@trydev.activeeon.com;10:24:17] ... 3 more 
```

**Comment by lpellegr** [comment]
Fixed by ow2-proactive/connector-r@c932156e4c73574db771703ec2cb1405e1e01a65.
