### ISSUE TITLE
Forked JVM executing a task using ProActive hangs  

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2309]
While working on [the decoupling between task and job identifiers](https://github.com/ow2-proactive/scheduling/pull/2304) I discovered that some tests are failing on my machine due to changes introduced with the Speed branch.

These tests were failing because the JVM started for executing a task in a forked process was never terminated.  The reason is that these tests were executing tasks involving ProActive code, thus starting a ProActive runtime in the JVM. Since a JVM exits when all non daemon threads are finished only, all forked tasks involving ProActive were never stopped.

At least three solutions are possible for solving the issue:

  1. Terminate all threads started by ProActive using `ProActiveRuntimeImpl.getProActiveRuntime().cleanJvmFromPA()`
  2. Remove ProActive usage from tasks (possible since ProActive is used for synchronization only and the same could be done using a file on the local filesystem)
  3. Call `System.exit(0)` as last step in `ForkedTaskExecutor#fromForkedJVM`

Solution 1 is not working since `cleanJvmFromPA` seems to let some RMI along with some internal ProActive threads running. 

Below is a thread dump for the JVM running the task after a call to `cleanJvmFromPA`:

```bash
lpellegr@oops:scheduling$ jstack 7047
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode):

"Attach Listener" daemon prio=10 tid=0x00007f7edc001000 nid=0x1c85 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" prio=10 tid=0x00007f7f3000e800 nid=0x1b88 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitoring the Futures" daemon prio=10 tid=0x00007f7f30a76000 nid=0x1bfe waiting on condition [0x00007f7f21597000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.objectweb.proactive.core.body.future.FutureMonitoring.monitoringDelay(FutureMonitoring.java:94)
	at org.objectweb.proactive.core.body.future.FutureMonitoring.run(FutureMonitoring.java:174)
	at java.lang.Thread.run(Thread.java:745)

"RMI TCP Connection(idle)" daemon prio=10 tid=0x00007f7eac003000 nid=0x1bfd waiting on condition [0x00007f7f21799000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007067c36a8> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"RMI RenewClean-[192.168.1.168:49750]" daemon prio=10 tid=0x00007f7f30802000 nid=0x1bfc in Object.wait() [0x00007f7f218d3000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007b02c7538> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007b02c7538> (a java.lang.ref.ReferenceQueue$Lock)
	at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(DGCClient.java:535)
	at java.lang.Thread.run(Thread.java:745)

"RMI Reaper" prio=10 tid=0x00007f7f30791000 nid=0x1be8 in Object.wait() [0x00007f7f21cdd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007067da0c0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007067da0c0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at sun.rmi.transport.ObjectTable$Reaper.run(ObjectTable.java:351)
	at java.lang.Thread.run(Thread.java:745)

"GC Daemon" daemon prio=10 tid=0x00007f7f30780800 nid=0x1be6 in Object.wait() [0x00007f7f224e5000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007067db2d8> (a sun.misc.GC$LatencyLock)
	at sun.misc.GC$Daemon.run(GC.java:117)
	- locked <0x00000007067db2d8> (a sun.misc.GC$LatencyLock)

"RMI RenewClean-[192.168.1.168:53147]" daemon prio=10 tid=0x00007f7f30780000 nid=0x1be5 in Object.wait() [0x00007f7f21dde000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007ae499308> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007ae499308> (a java.lang.ref.ReferenceQueue$Lock)
	at sun.rmi.transport.DGCClient$EndpointEntry$RenewCleanThread.run(DGCClient.java:535)
	at java.lang.Thread.run(Thread.java:745)

"process reaper" daemon prio=10 tid=0x00007f7f30760800 nid=0x1bda waiting on condition [0x00007f7f217d2000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007ae1361d0> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"RMI TCP Connection(idle)" daemon prio=10 tid=0x00007f7eac001000 nid=0x1bd0 waiting on condition [0x00007f7f21bdc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007067c36a8> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"RMI TCP Accept-0" daemon prio=10 tid=0x00007f7f306f3800 nid=0x1bc7 runnable [0x00007f7f21edf000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:399)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:371)
	at java.lang.Thread.run(Thread.java:745)

"RMI Scheduler(0)" daemon prio=10 tid=0x00007f7f306ef800 nid=0x1bc6 waiting on condition [0x00007f7f21fe0000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070667fa80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" daemon prio=10 tid=0x00007f7f300a7000 nid=0x1b9f runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007f7f300a4800 nid=0x1b9e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007f7f300a1800 nid=0x1b9d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007f7f3009f000 nid=0x1b9c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007f7f3007e000 nid=0x1b99 in Object.wait() [0x00007f7f28ba2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007066115f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007066115f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" daemon prio=10 tid=0x00007f7f3007c000 nid=0x1b98 in Object.wait() [0x00007f7f28ca3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000706611360> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x0000000706611360> (a java.lang.ref.Reference$Lock)

"VM Thread" prio=10 tid=0x00007f7f30077800 nid=0x1b97 runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007f7f30024000 nid=0x1b8d runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007f7f30026000 nid=0x1b8e runnable 

"GC task thread#2 (ParallelGC)" prio=10 tid=0x00007f7f30028000 nid=0x1b8f runnable 

"GC task thread#3 (ParallelGC)" prio=10 tid=0x00007f7f3002a000 nid=0x1b90 runnable 

"GC task thread#4 (ParallelGC)" prio=10 tid=0x00007f7f3002c000 nid=0x1b91 runnable 

"GC task thread#5 (ParallelGC)" prio=10 tid=0x00007f7f3002e000 nid=0x1b92 runnable 

"GC task thread#6 (ParallelGC)" prio=10 tid=0x00007f7f30030000 nid=0x1b93 runnable 

"GC task thread#7 (ParallelGC)" prio=10 tid=0x00007f7f30031800 nid=0x1b94 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f7f300c2000 nid=0x1ba0 waiting on condition 

JNI global references: 299
```

Solution 2 is the one currently applied (#2304) because it minimizes side effects while working. 

Solution 3 needs deeper investigation, especially to see if there is no usecase (e.g. using native tasks) that would interfer with such a behaviour.

This issue is labeled as a Story since I think that what to do should be discussed first.

**Comment by lpellegr** [comment]
Solution 2 is currently applied. However, it does not prevent users to write Java tasks that run ProActive Active Objects, or more generally non-daemon threads which are not cleaned properly. I think the problem should be reproduced and solution 3 retested as a solution.

**Comment by fviale** [comment]
fix merged.
