### ISSUE TITLE
TopologyManager's nodesOnHost map gets corrupted after several connection/disconnection

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2384]
Apparently, the synchronization on the topology variable is not enough, and, probably due to concurrency issues, the nodesOnHost map reaches an illegal state, which prevents afterwards new Nodes from being added to the topology.

The error printed is the following:
````
[2015-11-22 12:14:58,693 WARN    o.o.p.r.n.RMNodeConfigurator] Cannot properly configure the node pnp://172.16.11.227:1100/PA-AGENT_NODE because of an error during configuration phase
java.util.NoSuchElementException
	at java.util.LinkedList$ListItr.next(LinkedList.java:890)
	at org.ow2.proactive.resourcemanager.selection.topology.TopologyManager.addNode(TopologyManager.java:150)
	at org.ow2.proactive.resourcemanager.nodesource.RMNodeConfigurator.configureNode(RMNodeConfigurator.java:107)
	at sun.reflect.GeneratedMethodAccessor565.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
	at org.objectweb.proactive.Service.serve(Service.java:125)
	at org.ow2.proactive.resourcemanager.nodesource.RMNodeConfigurator.runActivity(RMNodeConfigurator.java:143)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by fviale** [comment]
The customer did not report any more occurence of this issue, so it can be closed
