### ISSUE TITLE
Node does not connect to given IP Address

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/scheduling#2388]
The ProActive Node has an option to connect it to a specific address. But that option does not ensure that if the address is an IP address the node will connect to that IP address.

Reproducing the problem:
Server machine network configuration:
```
eth0      Link encap:Ethernet  HWaddr 04:01:89:e0:ef:01
          inet addr:46.101.184.205  Bcast:46.101.191.255  Mask:255.255.192.0
          inet6 addr: fe80::601:89ff:fee0:ef01/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:232174 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41574 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:347767955 (347.7 MB)  TX bytes:4190661 (4.1 MB)
```
Node machine network configuration:
```
eth0      Link encap:Ethernet  HWaddr 04:01:89:e0:ff:01
          inet addr:46.101.221.71  Bcast:46.101.255.255  Mask:255.255.192.0
          inet6 addr: fe80::601:89ff:fee0:ff01/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:108725 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23787 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:163352477 (163.3 MB)  TX bytes:1778832 (1.7 MB)
```

The machines are rented at digital ocean. There is a private network available but it is deactivated for both virtual machines.

After starting the Scheduler with ``./proactive-server -ln 0``` following output is printed:

```
Starting the scheduler...
Starting the resource manager...
The resource manager with 0 local nodes created on pnp://10.19.0.11:64738/
The scheduler created on pnp://10.19.0.11:64738/
Starting the web applications...
The web application /rest created on http://10.19.0.11:8080/rest
The web application /scheduler created on http://10.19.0.11:8080/scheduler
The web application /studio created on http://10.19.0.11:8080/studio
The web application /rm created on http://10.19.0.11:8080/rm
*** Get started at http://10.19.0.11:8080 ***
```

The Scheduler web interface in available through its public IP address 42.X.X.X.

**Starting the Node**

The node is started through ```./proactive-node -Dproactive.useIPaddress=true -Dproactive.net.interface=eth0 -r  pnp://46.101.184.205:64738/```

The output of the node is the following:
```
java.io.IOException: Lookup of org.ow2.proactive.resourcemanager.authentication.                                                                                                                                                             RMAuthentication at pnp://46.101.184.205:64738/RMAUTHENTICATION failed
Unable to join the Resource Manager at pnp://46.101.184.205:64738/
org.ow2.proactive.resourcemanager.exception.RMException: Cannot join the Resourc                                                                                                                                                             e Manager at pnp://46.101.184.205:64738/RMAUTHENTICATION due to Lookup of org.ow                                                                                                                                                             2.proactive.resourcemanager.authentication.RMAuthentication at pnp://46.101.184.                                                                                                                                                             205:64738/RMAUTHENTICATION failed
        at org.ow2.proactive.resourcemanager.frontend.RMConnection.waitAndJoin(R                                                                                                                                                             MConnection.java:111)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.joinResourceMan                                                                                                                                                             ager(RMNodeStarter.java:989)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.registerInRM(RM                                                                                                                                                             NodeStarter.java:1025)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.connectToResour                                                                                                                                                             ceManager(RMNodeStarter.java:404)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.doMain(RMNodeSt                                                                                                                                                             arter.java:374)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.main(RMNodeStar                                                                                                                                                             ter.java:333)
Caused by: java.io.IOException: Lookup of org.ow2.proactive.resourcemanager.auth                                                                                                                                                             entication.RMAuthentication at pnp://46.101.184.205:64738/RMAUTHENTICATION faile                                                                                                                                                             d
        at org.objectweb.proactive.api.PAActiveObject.lookupActive(PAActiveObjec                                                                                                                                                             t.java:1426)
        at org.ow2.proactive.authentication.Connection.lookupAuthentication(Conn                                                                                                                                                             ection.java:100)
        at org.ow2.proactive.authentication.Connection.waitAndConnect(Connection                                                                                                                                                             .java:150)
        at org.ow2.proactive.resourcemanager.frontend.RMConnection.waitAndJoin(R                                                                                                                                                             MConnection.java:109)
        ... 5 more
Caused by: org.objectweb.proactive.core.ProActiveException: java.lang.NullPointe                                                                                                                                                             rException
        at org.objectweb.proactive.core.remoteobject.RemoteObjectHelper.generate                                                                                                                                                             dObjectStub(RemoteObjectHelper.java:202)
        at org.objectweb.proactive.api.PAActiveObject.lookupActive(PAActiveObjec                                                                                                                                                             t.java:1414)
        ... 8 more
Caused by: java.lang.NullPointerException
        at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.getClas                                                                                                                                                             sName(RemoteObjectAdapter.java:236)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectHelper.generate                                                                                                                                                             dObjectStub(RemoteObjectHelper.java:184)
        ... 9 more

```

The log of the node reveals that it tried to connect to the private IP address

```
[2015-11-25 10:31:39,014 WARN ] [t] [NODE.RemoteObjectSet.handleProtocolException] [ROAdapter] Skipping default protocol pnp because of received exception
org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://10.19.0.11:64738/RMAUTHENTICATION
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:117)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObject.receiveMessage(PNPRemoteObject.java:82)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectSet.receiveMessage(RemoteObjectSet.java:205)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.receiveMessage(RemoteObjectAdapter.java:151)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.getClassName(RemoteObjectAdapter.java:234)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectHelper.generatedObjectStub(RemoteObjectHelper.java:184)
        at org.objectweb.proactive.api.PAActiveObject.lookupActive(PAActiveObject.java:1414)
        at org.ow2.proactive.authentication.Connection.lookupAuthentication(Connection.java:100)
        at org.ow2.proactive.authentication.Connection.waitAndConnect(Connection.java:150)
        at org.ow2.proactive.resourcemanager.frontend.RMConnection.waitAndJoin(RMConnection.java:109)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.joinResourceManager(RMNodeStarter.java:989)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.registerInRM(RMNodeStarter.java:1025)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.connectToResourceManager(RMNodeStarter.java:404)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.doMain(RMNodeStarter.java:374)
        at org.ow2.proactive.resourcemanager.utils.RMNodeStarter.main(RMNodeStarter.java:333)
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPIOException: Failed to connect to /10.19.0.11:64738
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannel.<init>(PNPAgent.java:377)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:317)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:305)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:187)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:175)
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:115)
        ... 14 more
Caused by: java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Even though the network configuration might be complex or unique. Nevertheless it might be useful to have an option which connects to an IP address.

**Comment by tobwiens** [comment]
I did additional tests by adding the netmask (CIDR) property:
```
./proactive-node -Dproactive.useIPaddress=true -Dproactive.net.interface=eth0 -Dproactive.net.netmask=46.101.143.54/14 -r pnp://46.101.143.54:64738/
```
It's the same error.

**Comment by fviale** [comment]
The server output says that the scheduler was bound on the private IP address:
```
The resource manager with 0 local nodes created on pnp://10.19.0.11:64738/
```

Which is not what you want.
The settings in config/network/server.ini must be changed on the server and the following line added:
proactive.net.netmask=46.101.184.0/24

By doing that, you should see on the scheduler output:
```
The resource manager with 0 local nodes created on pnp://46.101.184.205:64738/
```

In addition, in the network configuration of the node, you show that its IP address should be 46.101.221.71

But you set the netmask property on the node level to -Dproactive.net.netmask=46.101.213.4/18 
I suppose this is correct because of the netmask of 18 you choose but it's a bit confusing. Personnally I would put -Dproactive.net.netmask=46.101.221.0/24 for clarity 

Finally, on the node level, remove the -Dproactive.net.interface=eth0 option if you use netmask.

**Comment by tobwiens** [comment]
Okay, 

I will try again with those settings, if it was just configuration then we can close this.

**Comment by tobwiens** [comment]
I started the proactive Scheduler with 
```
-Dproactive.net.netmask=46.101.208.219/18
```

This is the log: works fine.
```
Starting the scheduler...
Starting the resource manager...
The resource manager with 0 local nodes created on pnp://46.101.208.219:64738/
The scheduler created on pnp://46.101.208.219:64738/
Starting the web applications...
The web application /rest created on http://46.101.208.219:8080/rest
The web application /studio created on http://46.101.208.219:8080/studio
The web application /scheduler created on http://46.101.208.219:8080/scheduler
The web application /rm created on http://46.101.208.219:8080/rm
*** Get started at http://46.101.208.219:8080 ***

```

Then I start the node with 
```
-Dproactive.useIPaddress=true -r  pnp://46.101.208.219:64738
```

The node is stuck and does not log or do anything after 5 minutes. Here is the log:
```
[2016-02-03 05:39:30,849 INFO ] [t] [NODE.RMNodeStarter.configureLogging] Configured log4j using /root/scheduling/config/log/node.properties
[2016-02-03 05:39:30,939 INFO ] [t] [NODE.RMNodeStarter.selectNetworkInterface] Node will be bounded to the following network interface eth0
[2016-02-03 05:39:33,690 INFO ] [t] [NODE.Tools.logAvailableScriptEngines] Available script engines: Oracle Nashorn(1.8.0_60),exec(1.0),java(1.0),JSR 223 JRuby Engine(9.0.1.0),jython(2.7.0),bash(4.3.42(1)-release),Groovy Scripting Engine(2.0),docker-compose(0.0.1),cmd(Could not determine version)
```

The version is 7.0.0.


I found following logs on the Scheduler side:
```
org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message
 to pnp://10.19.0.68:45498/HalfBody_pa.stub.org.ow2.proactive.resourcemanager.no
desource.dataspace._StubDataSpaceNodeConfigurationAgent%23configureNode_121b3650
-152a6b73640--7ffe--ea11b4c4635fd7f8-121b3650-152a6b73640--8000
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage
.java:117)
        at org.objectweb.proactive.extensions.pnp.PNPRemoteObject.receiveMessage(PNPRemoteObject.java:82)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectSet.receiveMessage(RemoteObjectSet.java:205)
        at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.receiveMessage(RemoteObjectAdapter.java:151)
        at org.objectweb.proactive.core.remoteobject.SynchronousProxy.reify(SynchronousProxy.java:78)
        at pa.stub.org.objectweb.proactive.core.body._StubUniversalBody.receiveReply(_StubUniversalBody.java)
        at org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter.receiveReply(UniversalBodyRemoteObjectAdapter.java:136)
        at org.objectweb.proactive.core.body.reply.ReplyImpl.send(ReplyImpl.java:104)
 at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:620)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.serve(Service.java:125)
        at org.ow2.proactive.authentication.AuthenticationImpl.runActivity(AuthenticationImpl.java:240)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPIOException: Failed to connect to /10.19.0.68:45498
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannel.<init>(PNPAgent.java:377)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:317)
        at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:305)
        at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:187)
 at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:175)
        at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:115)
        ... 14 more
Caused by: java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
 at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more


```


Interesting is that the Scheduler tried to connect to pnp://10.19.0.68:45498

**Comment by tobwiens** [comment]
Starting the node with:
```
-Dproactive.net.netmask=46.101.209.33/18  -Dproactive.useIPaddress=true -r  pnp://46.101.208.219:64738
```

Binding it to the correct network interface through the netmask resulted in success: 
```
Connected to the resource manager at pnp://46.101.208.219:64738
```

Issue solved.

**Comment by fviale** [comment]
You forgot to put as well the property -Dproactive.net.netmask=46.101.213.4/18  on the node, that's why.
