### ISSUE TITLE
permission denied error with nodes file in non-forked mode

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2403]
The following error occurs in non-forked mode when executing a task. This doesn't occured immediately, but after a few scheduler restarts. Apparently, the method writeNodesFile has been designed for forked mode only and is bugged in non-forked mode. It attemps to create a temporary folder in the current directory i.e. new File("."), which makes no sense in non-forked. Additionnally, the nodes file is deleted on JVM exit. 

[2015-12-07 18:53:36,724 ERROR           o.o.p.s.u.TaskLogger] task 454t2 (End) error
java.io.IOException: Permission non accordée
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.writeNodesFile(InProcessTaskExecutor.java:163)
        at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:103)
        at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:172)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
        at org.objectweb.proactive.Service.fifoServing(Service.java:146)
        at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fviale** [comment]
fix merged
