### ISSUE TITLE
 Failed to terminate task error due to database deadlock

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2407]
Affects version 6.3.1-RC2 (4bd33223bff3a8c511d2c3c3a41e85e990aceeee)

After this error, the job remains in running state and the node remains busy. The job cannot be killed. The only workaround is to restart the scheduler

```
[2015-12-09 11:29:57,024 WARN   o.o.p.s.c.d.TransactionHelper] Maximum number of transaction retries exceeded, giving up. Last exception: 
org.hibernate.exception.LockAcquisitionException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:94)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy32.executeUpdate(Unknown Source)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:95)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:413)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:282)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1264)
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:116)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.removeJobScripts(SchedulerDBManager.java:655)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.removeJobRuntimeData(SchedulerDBManager.java:669)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.access$1600(SchedulerDBManager.java:79)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$27.executeWork(SchedulerDBManager.java:1188)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$27.executeWork(SchedulerDBManager.java:1140)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.tryRunWithTransaction(TransactionHelper.java:69)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithTransaction(TransactionHelper.java:41)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithTransaction(TransactionHelper.java:29)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.runWithTransaction(SchedulerDBManager.java:1643)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.updateAfterTaskFinished(SchedulerDBManager.java:1140)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.updateAfterTaskFinished(SchedulerDBManager.java:1135)
	at org.ow2.proactive.scheduler.core.LiveJobs.terminateTask(LiveJobs.java:632)
	at org.ow2.proactive.scheduler.core.LiveJobs.taskTerminatedWithResult(LiveJobs.java:457)
	at org.ow2.proactive.scheduler.core.SchedulingService$12.run(SchedulingService.java:579)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
	... 26 more
Caused by: java.sql.SQLException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 40 more
Caused by: ERROR 40001: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.locks.Deadlock.buildException(Unknown Source)
	at org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(Unknown Source)
	at org.apache.derby.impl.services.locks.AbstractPool.lockObject(Unknown Source)
	at org.apache.derby.impl.services.locks.ConcurrentPool.lockObject(Unknown Source)
	at org.apache.derby.impl.store.raw.xact.RowLocking2.lockRecordForRead(Unknown Source)
	at org.apache.derby.impl.store.access.conglomerate.OpenConglomerate.lockPositionForRead(Unknown Source)
	at org.apache.derby.impl.store.access.conglomerate.GenericScanController.fetchRows(Unknown Source)
	at org.apache.derby.impl.store.access.heap.HeapScan.fetchNext(Unknown Source)
	at org.apache.derby.impl.sql.execute.TableScanResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteCascadeResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteCascadeResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 34 more
[2015-12-09 11:29:57,401 ERROR    o.o.p.s.c.SchedulingService] Failed to terminate task 17960000
org.ow2.proactive.db.DatabaseManagerException: DB operation failed
	at org.ow2.proactive.db.DatabaseManagerExceptionHandler.handle(DatabaseManagerExceptionHandler.java:152)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithTransaction(TransactionHelper.java:59)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithTransaction(TransactionHelper.java:29)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.runWithTransaction(SchedulerDBManager.java:1643)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.updateAfterTaskFinished(SchedulerDBManager.java:1140)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.updateAfterTaskFinished(SchedulerDBManager.java:1135)
	at org.ow2.proactive.scheduler.core.LiveJobs.terminateTask(LiveJobs.java:632)
	at org.ow2.proactive.scheduler.core.LiveJobs.taskTerminatedWithResult(LiveJobs.java:457)
	at org.ow2.proactive.scheduler.core.SchedulingService$12.run(SchedulingService.java:579)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.LockAcquisitionException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:94)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy32.executeUpdate(Unknown Source)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:95)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:413)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:282)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1264)
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:116)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.removeJobScripts(SchedulerDBManager.java:655)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.removeJobRuntimeData(SchedulerDBManager.java:669)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.access$1600(SchedulerDBManager.java:79)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$27.executeWork(SchedulerDBManager.java:1188)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$27.executeWork(SchedulerDBManager.java:1140)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.tryRunWithTransaction(TransactionHelper.java:69)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithTransaction(TransactionHelper.java:41)
	... 12 more
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
	... 26 more
Caused by: java.sql.SQLException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 40 more
Caused by: ERROR 40001: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SCRIPT_DATA, (70,24)
  Waiting XID : {60563657, U} , SCHEDULER, delete from SCRIPT_DATA where ID in (select forkedjava1_.ENV_SCRIPT_ID from FORKED_JAVA_TASK_DATA forkedjava1_ where forkedjava1_.JOB_ID=?) or ID in (select nativetask2_.GEN_SCRIPT_ID from NATIVE_TASK_DATA nativetask2_ where nativetask2_.JOB_ID=?) or ID in (select taskdata3_.PRE_SCRIPT_ID from TASK_DATA taskdata3_ where taskdata3_.TASK_ID_JOB=?) or ID in (select taskdata4_.POST_SCRIPT_ID from TASK_DATA taskdata4_ where taskdata4_.TASK_ID_JOB=?) or ID in (select taskdata5_.CLEAN_SCRIPT_ID from TASK_DATA taskdata5_ where taskdata5_.TASK_ID_JOB=?) or ID in (select taskdata6_.FLOW_SCRIPT_ID from TASK_DATA taskdata6_ where taskdata6_.TASK_ID_JOB=?) or ID in (select scripttask7_.TASK_SCRIPT_ID from SCRIPT_TASK_DATA scripttask7_ where scripttask7_.JOB_ID=?) or JOB_ID=?
  Granted XID : {60563666, X} 
Lock : TABLE, FORKED_JAVA_TASK_DATA, Tablelock
  Waiting XID : {60563666, IX} , SCHEDULER, insert into FORKED_JAVA_TASK_DATA (ARGUMENTS, JOB_ID, TASK_ID, CLASS_NAME, CLASSPATH, ENV_SCRIPT_ID, JAVA_HOME, JVM_ARGUMENTS, WORK_DIR, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  Granted XID : {60563657, X} 
. The selected victim is XID : 60563657.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.locks.Deadlock.buildException(Unknown Source)
	at org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(Unknown Source)
	at org.apache.derby.impl.services.locks.AbstractPool.lockObject(Unknown Source)
	at org.apache.derby.impl.services.locks.ConcurrentPool.lockObject(Unknown Source)
	at org.apache.derby.impl.store.raw.xact.RowLocking2.lockRecordForRead(Unknown Source)
	at org.apache.derby.impl.store.access.conglomerate.OpenConglomerate.lockPositionForRead(Unknown Source)
	at org.apache.derby.impl.store.access.conglomerate.GenericScanController.fetchRows(Unknown Source)
	at org.apache.derby.impl.store.access.heap.HeapScan.fetchNext(Unknown Source)
	at org.apache.derby.impl.sql.execute.TableScanResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteCascadeResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.DeleteCascadeResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 34 more
```

**Comment by fviale** [comment]
Duplicate of #2443
