### ISSUE TITLE
New PA variable for exit code

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2411]
It is currently not possible to get exit code properly, especially with native tasks. The documentation states that exit code is put in _result_ variable. However, this is true when command executes with success only (i.e. exit code is 0). If command fails, a stacktrace is appended to the _result_ variable.

Below is an example with invalid command `df -hhh`:

```
Failed to execute task: java.io.IOException: Cannot run program "df ": error=2, No such file or directory
	at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:341)
	at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:112)
	at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.fromForkedJVM(ForkedTaskExecutor.java:328)
	at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.main(ForkedTaskExecutor.java:321)
Caused by: org.ow2.proactive.scripting.ScriptException: java.io.IOException: Cannot run program "df ": error=2, No such file or directory
	at jsr223.nativeshell.executable.ExecutableScriptEngine.eval(ExecutableScriptEngine.java:48)
	at jsr223.nativeshell.executable.ExecutableScriptEngine.eval(ExecutableScriptEngine.java:136)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
	at org.ow2.proactive.scripting.Script.execute(Script.java:318)
	at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76)
	at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:337)
	... 3 more
``` 

Brian and I discussed about this behaviour since a potential customer requested a solution to retrieve the return code for any possible command. We think that a new variable such as _exitCode_ or _exitValue_ should be introduced and value set automatically.

**Comment by fviale** [comment]
improvement added
