### ISSUE TITLE
Add defensive checks to SchedulerClient and SmartProxy to avoid NPE

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2444]
The following exception is thrown:
The NPE hides the underlying problem (was it a disconnection ?, a wrong usage of the API ? more defensive check should be added)
```
java.lang.NullPointerException
        at org.ow2.proactive.scheduler.rest.SchedulerClient.restApi(SchedulerCli
ent.java:952)
        at org.ow2.proactive.scheduler.rest.SchedulerClient.isConnected(Schedule
rClient.java:402)
        at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.ow2.proactive.scheduler.rest.SessionHandler.invoke(SessionHandler
.java:58)
        at com.sun.proxy.$Proxy15.isConnected(Unknown Source)
        at org.ow2.proactive.scheduler.smartproxy.common.AbstractSmartProxy.isCo
nnected(AbstractSmartProxy.java:707)
        at fr.cea.distributed.proactive.SchedulerProxyStarter.getSchedulerProxyU
serInterface(SchedulerProxyStarter.java:76)
        at fr.cea.distributed.proactive.ProActiveServerManager.getSchedulerProxy
(ProActiveServerManager.java:52)
        at fr.cea.distributed.proactive.ProActiveJob.updateTaskState(ProActiveJo
b.java:413)
        at fr.cea.distributed.proactive.ProActiveSchedulerListener$ProActiveSche
dulerListenerExecutor.taskStateUpdatedEvent(ProActiveSchedulerListener.java:215)
 
        at fr.cea.distributed.proactive.ProActiveSchedulerListener$2.run(ProActi
veSchedulerListener.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:724)
Exception for Finished TestAutoTask JobID 47715
CIVA: TaskCancelled 39
TaskComputationCanceled - nbBatchFilesFinished 187 Nb total 188
Exception for Finished TestAutoTask JobID 47715
null
```

**Comment by fviale** [comment]
merged
