### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by winghc** [ow2-proactive/scheduling#2470]
Environment:

Host: 3 hosts
Nodes:  One NodeStarter on each node
ulimit -u 1032034

Each Job is to run one bash shell, which actually call hive command ( Java client ).    I gain the following "OutOfMemoryError"  

[2016-02-25 14:12:43,506 INFO      o.o.p.r.s.SelectionManager] "scheduler" requested 10 nodes with ArbitraryTopologyDescriptor
[2016-02-25 14:12:43,525 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 10 nodes 
[2016-02-25 14:12:44,118 INFO            o.o.p.s.u.TaskLogger] task 1365t10 (Task175) creating forked task launcher
[2016-02-25 14:12:44,144 INFO            o.o.p.s.u.TaskLogger] task 1365t10 (Task175) started on m-dn02(node: SSH-dn02-2)
[2016-02-25 14:12:44,304 ERROR           o.o.p.s.u.TaskLogger] task 1365t10 (Task175) error
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
    at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
    at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:167)
    at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:215)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper.mountAny(VFSMountManagerHelper.java:208)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.mountFirstAvailableFileSystem(VFSSpacesMountManagerImpl.java:304)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.ensureVirtualSpaceIsMounted(VFSSpacesMountManagerImpl.java:269)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:168)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:138)
    at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveInputOutput(DataSpacesImpl.java:213)
    at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveDefaultInputOutput(DataSpacesImpl.java:173)
    at org.objectweb.proactive.extensions.dataspaces.api.PADataSpaces.resolveDefaultOutput(PADataSpaces.java:237)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$2.call(TaskProActiveDataspaces.java:165)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$2.call(TaskProActiveDataspaces.java:162)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpace(TaskProActiveDataspaces.java:187)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:162)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:81)
    at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:53)
    at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tobwiens** [comment]
Hello, 

1)Does you task contain a lot of data? The out of memory error seems to be thrown inside the dataspaces. The dataspaces perform memory operations from the server to the executing nodes. 

2) Does your hive processing run on the same machine and might utilizes all available resources?

**Comment by fviale** [comment]
Usually this error is due to the linux configuration limitations, there is indeed a limit to the number of threads and processes which can be created by user, and the number of files opened.

You can try to set the following values in /etc/security/limits.conf (example config for RedHat) of all nodes machines, where "username" must be replaced by the account running proactive nodes:
username hard nofile 65535
username soft nofile 65535
username soft nproc 65535 
username hard nproc 65535 
If you see files in /etc/security/limits.d/ folder, you might need to port the settings to these files too.

**Comment by winghc** [comment]
1)Does you task contain a lot of data? The out of memory error seems to be thrown inside the dataspaces. The dataspaces perform memory operations from the server to the executing nodes.

the task is hive client job which submit job to hadoop cluster,  client just gain the map/reduce statistics information/log.  Does this matter?  How Proactive consume those log info?

**Comment by tingking23** [comment]
@fviale  
we already changed that limit. there it is , is that worng?
POSIX message queues      819200 bytes
open files                               65536
stack size                              10240 kbytes
max user processes              1032034
prpe size                                8(512 bytes)
max locked memory               64 kbytes
others all set  unlimited.          And our system is redhat 6.2  --X64

**Comment by fviale** [comment]
Try to login to all the nodes and get the output of ulimit -a on the account used to start the nodes. Maybe one node is misconfigured ? 
Eventually, to make really sure, you can use the RM portal, click on a green node on each host, then on Script Console, then select bash, then enter "ulimit -a", click on Execute and watch the limits that the ProActive nodes actually have.

**Comment by tingking23** [comment]
@fviale 
i do it what you suggest ,it is the same things  as i write the limit  before. By the way ,we used Workflows & Scheduling 7.1.2

**Comment by fviale** [comment]
Ok, could you execute on some nodes, again using the Script Console, and this time choosing groovy as a script engine the following code:

println java.lang.management.ManagementFactory.getThreadMXBean().getThreadCount()

This will print the number of threads alive in the node JVM, so we can check if the JVM contains a huge number of dormant threads.

Unrelated but It's a bit complicated to run a bash script that starts a JVM. 

To make things simpler, you could eventually write a groovy script which would directly call your Hive Java API. And if you need to load your Hive API jars you can use a fork environment script to customize the forked JVM process parameters. 

Simply add a fork environment groovy script to your task and directly use the forkEnvironment variable which is available inside the script. The forkEnvironment is a Java object which has the following API:
http://www.activeeon.com/public_content/releases/ProActive/dev/ProActiveWorkflowsScheduling-javadoc/org/ow2/proactive/scheduler/common/task/ForkEnvironment.html

Example:

```groovy
forkEnvironment.addAdditionalClasspath("/absolute/path/to/hive/jars/*")
```
After that the main groovy Executable script of your task should be able to use the Hive API directly (by using import directives)

**Comment by winghc** [comment]
update limits.conf  is the solution
