### ISSUE TITLE
Task with error " Resource down"

### ISSUE THREAD

**Issue by tingking23** [ow2-proactive/scheduling#2473]
System environment: redhat 6.2   x64  ;  two host  A  ,  B
1. proactive start with host A and create 4 nodes 
2. add 1 nodes from host B to RM
3. run a workflow that have 9 task and then 1 task failed with error Status "Resource down" after running 
   19m28s. 

ps: all 5 nodes down 2 with fished that workflow,only 3 alive on host A.

Any ideas?

[2016-02-29 13:45:51,683 INFO      o.o.p.r.s.SelectionManager] "scheduler" requested 8 nodes with ArbitraryTopologyDescriptor
[2016-02-29 13:45:51,703 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 8 nodes 
[2016-02-29 13:45:51,865 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) creating forked task launcher
[2016-02-29 13:45:51,964 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) started on m-dn03(node: local-LocalNodes-11)
[2016-02-29 13:54:24,894 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) node failed
org.objectweb.proactive.core.body.exceptions.SendRequestCommunicationException: [Proxy] Exception occurred in reifyAsSynchronous while sending request for methodcall = getProgress from pnp://m-dn03:64738/HalfBody_pa.stub.org.ow2.proactive.scheduler.task._StubTaskLauncher%23doTask_496ccba-1532abb29bf--7ede--7088c88b95ab06c8-496ccba-1532abb29bf--8000 to pnp://m-dn03:36927/ActiveObject_org.ow2.proactive.scheduler.task.TaskLauncher_da18c4d-1532abb4704--7fc8--a6757a603c115765-da18c4d-1532abb4704--8000
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:331)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.invokeOnBody(AbstractBodyProxy.java:172)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reify(AbstractBodyProxy.java:123)
    at pa.stub.org.ow2.proactive.scheduler.task._StubTaskLauncher.getProgress(_StubTaskLauncher.java)
    at org.ow2.proactive.scheduler.core.SchedulingService.pingTaskNode(SchedulingService.java:795)
    at org.ow2.proactive.scheduler.core.NodePingThread$1.run(NodePingThread.java:28)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://m-dn03:36927/ActiveObject_org.ow2.proactive.scheduler.task.TaskLauncher_da18c4d-1532abb4704--7fc8--a6757a603c115765-da18c4d-1532abb4704--8000
    at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:117)
    at org.objectweb.proactive.extensions.pnp.PNPRemoteObject.receiveMessage(PNPRemoteObject.java:82)
    at org.objectweb.proactive.core.remoteobject.RemoteObjectSet.receiveMessage(RemoteObjectSet.java:205)
    at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.receiveMessage(RemoteObjectAdapter.java:151)
    at org.objectweb.proactive.core.remoteobject.SynchronousProxy.reify(SynchronousProxy.java:78)
    at pa.stub.org.objectweb.proactive.core.body._StubUniversalBody.receiveRequest(_StubUniversalBody.java)
    at org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter.receiveRequest(UniversalBodyRemoteObjectAdapter.java:140)
    at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:236)
    at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:147)
    at org.objectweb.proactive.core.body.HalfBody$HalfLocalBodyStrategy.sendRequest(HalfBody.java:238)
    at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:446)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequestInternal(UniversalBodyProxy.java:438)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:412)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:352)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:327)
    ... 10 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPHeartbeatTimeoutException: Hearthbeat not received in time (9000 ms)
    at org.objectweb.proactive.extensions.pnp.PNPAgent$Parking.unlockDueToDisconnection(PNPAgent.java:627)
    at org.objectweb.proactive.extensions.pnp.PNPAgent$Parking.run(PNPAgent.java:617)
    at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
    at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
    at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    ... 1 more
[2016-02-29 13:54:24,898 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) number of retry on failure left 1
[2016-02-29 13:54:24,959 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04)  is waiting for restart
[2016-02-29 13:55:33,415 INFO      o.o.p.r.s.SelectionManager] "scheduler" requested 1 nodes with ArbitraryTopologyDescriptor
[2016-02-29 13:55:33,446 INFO      o.o.p.r.s.SelectionManager] "scheduler" will get 1 nodes 
[2016-02-29 13:55:33,466 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) creating forked task launcher
[2016-02-29 13:55:33,701 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) started on m-dn03(node: local-LocalNodes-14)
[2016-02-29 14:13:28,039 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) node failed
org.objectweb.proactive.core.body.exceptions.SendRequestCommunicationException: [Proxy] Exception occurred in reifyAsSynchronous while sending request for methodcall = getProgress from pnp://m-dn03:64738/HalfBody_pa.stub.org.ow2.proactive.scheduler.task._StubTaskLauncher%23doTask_496ccba-1532abb29bf--7edc--7088c88b95ab06c8-496ccba-1532abb29bf--8000 to pnp://m-dn03:35568/ActiveObject_org.ow2.proactive.scheduler.task.TaskLauncher_199c87f5-1532b97c96d--7ff6--7425b4a113131a03-199c87f5-1532b97c96d--8000
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:331)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.invokeOnBody(AbstractBodyProxy.java:172)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reify(AbstractBodyProxy.java:123)
    at pa.stub.org.ow2.proactive.scheduler.task._StubTaskLauncher.getProgress(_StubTaskLauncher.java)
    at org.ow2.proactive.scheduler.core.SchedulingService.pingTaskNode(SchedulingService.java:795)
    at org.ow2.proactive.scheduler.core.NodePingThread$1.run(NodePingThread.java:28)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.objectweb.proactive.core.exceptions.IOException6: Failed to send PNP message to pnp://m-dn03:35568/ActiveObject_org.ow2.proactive.scheduler.task.TaskLauncher_199c87f5-1532b97c96d--7ff6--7425b4a113131a03-199c87f5-1532b97c96d--8000
    at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:117)
    at org.objectweb.proactive.extensions.pnp.PNPRemoteObject.receiveMessage(PNPRemoteObject.java:82)
    at org.objectweb.proactive.core.remoteobject.RemoteObjectSet.receiveMessage(RemoteObjectSet.java:205)
    at org.objectweb.proactive.core.remoteobject.RemoteObjectAdapter.receiveMessage(RemoteObjectAdapter.java:151)
    at org.objectweb.proactive.core.remoteobject.SynchronousProxy.reify(SynchronousProxy.java:78)
    at pa.stub.org.objectweb.proactive.core.body._StubUniversalBody.receiveRequest(_StubUniversalBody.java)
    at org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter.receiveRequest(UniversalBodyRemoteObjectAdapter.java:140)
    at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:236)
    at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:147)
    at org.objectweb.proactive.core.body.HalfBody$HalfLocalBodyStrategy.sendRequest(HalfBody.java:238)
    at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:446)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequestInternal(UniversalBodyProxy.java:438)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:412)
    at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:352)
    at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:327)
    ... 10 more
Caused by: org.objectweb.proactive.extensions.pnp.exception.PNPIOException: Failed to connect to m-dn03/21.244.128.43:35568
    at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannel.<init>(PNPAgent.java:377)
    at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:317)
    at org.objectweb.proactive.extensions.pnp.PNPAgent$PNPClientChannelCache.getChannel(PNPAgent.java:305)
    at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:187)
    at org.objectweb.proactive.extensions.pnp.PNPAgent.sendMsg(PNPAgent.java:175)
    at org.objectweb.proactive.extensions.pnp.PNPROMessage.send(PNPROMessage.java:115)
    ... 24 more
Caused by: java.net.ConnectException: Connection refused: m-dn03/21.244.128.43:35568
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    ... 3 more
[2016-02-29 14:13:28,041 INFO            o.o.p.s.u.TaskLogger] task 1555t2 (job04) number of retry on failure left 0

**Comment by winghc** [comment]
Hi,  this is actually caused by node die on host.   pls post the server log where the node gone on hosts A. 

By the way, set  log4j's level be 'debug' on that host to capture more detailed log
