### ISSUE TITLE
Files can be left over in a node scratch dir after a kill

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2479]
The following node logs show the problem
```
[2016-03-03 18:40:22,599 INFO ] [1t0] [NODE.TaskLauncher.doTask] Task started job_native_4_hosts : task1
[2016-03-03 18:40:22,633 INFO ] [1t0] [NODE.TaskProActiveDataspaces.initDataSpaces] Configuring dataspaces for app 1 on local-extra_0
[2016-03-03 18:40:22,716 INFO ] [1t0] [NODE.TaskProActiveDataspaces.initDataSpaces] SCRATCH space is file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM721862974/local-extra_0/1/2065745511
[2016-03-03 18:40:22,850 INFO ] [1t0] [NODE.TaskLauncher.doTask] Task working dir: H:\Users\fviale\AppData\Local\Temp\PA_JVM721862974\local-extra_0\1\2065745511
[2016-03-03 18:40:22,851 INFO ] [1t0] [NODE.TaskLauncher.doTask] Input space: H:\Users\fviale\workspace\fork\scheduling\data\defaultinput\demo
[2016-03-03 18:40:22,851 INFO ] [1t0] [NODE.TaskLauncher.doTask] Output space: H:\Users\fviale\workspace\fork\scheduling\data\defaultoutput\demo
[2016-03-03 18:40:22,851 INFO ] [1t0] [NODE.TaskLauncher.doTask] User space: H:\Users\fviale\workspace\fork\scheduling\data\defaultuser\demo
[2016-03-03 18:40:22,851 INFO ] [1t0] [NODE.TaskLauncher.doTask] Global space: H:\Users\fviale\workspace\fork\scheduling\data\defaultglobal
[2016-03-03 18:40:29,097 INFO ] [1t0] [NODE.TaskLauncher.terminate] Task terminated
[2016-03-03 18:45:10,194 INFO ] [t] [NODE.RMNodeStarter.configureLogging] Configured log4j using H:\Users\fviale\workspace\fork\scheduling\config\log\node.properties
[2016-03-03 18:45:10,197 INFO ] [t] [NODE.RMNodeStarter.configure] Using ProActive configuration file : H:\Users\fviale\workspace\fork\scheduling\config\network\node.ini
[2016-03-03 18:45:10,299 INFO ] [t] [NODE.RMNodeStarter.selectNetworkInterface] Node will be bounded to the following network interface eth7
[2016-03-03 18:45:12,591 INFO ] [t] [NODE.Tools.logAvailableScriptEngines] Available script engines: bash(3.1.0(1)-release),cmd(2),Groovy Scripting Engine(2.0),JSR 223 JRuby Engine(9.0.1.0),docker-compose(0.0.2),Oracle Nashorn(1.8.0_73),jython(2.7.0),java(1.0),exec(1.0)
[2016-03-03 18:45:12,592 INFO ] [t] [NODE.RMNodeStarter.joinResourceManager] Joining Resource Manager at pnp://precision:1199/
[2016-03-03 18:45:12,625 INFO ] [t] [NODE.RMNodeStarter.joinResourceManager] Resource Manager joined.
[2016-03-03 18:45:12,807 INFO ] [t] [NODE.RRDDataStore.initDatabase] Using existing RRD database: H:\Users\fviale\workspace\fork\scheduling\data\local-extra_statistics.rrd
[2016-03-03 18:45:12,917 INFO ] [t] [NODE.AbstractJMXHelper.boot] Started JMX RMI connector server at service:jmx:rmi:///jndi/rmi://precision:56176/rmnode
[2016-03-03 18:45:12,999 INFO ] [t] [NODE.AbstractJMXHelper.boot] Started JMX RO connector server at service:jmx:ro:///jndi/pnp://precision:56154/rmnode
[2016-03-03 18:45:13,004 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Adding node local-extra_0 to Resource Manager.
[2016-03-03 18:45:13,089 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Node pnp://precision:56154/local-extra_0 added.
[2016-03-03 18:45:13,111 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Adding node local-extra_1 to Resource Manager.
[2016-03-03 18:45:13,161 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Node pnp://precision:56154/local-extra_1 added.
[2016-03-03 18:45:13,164 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Adding node local-extra_2 to Resource Manager.
[2016-03-03 18:45:13,401 INFO ] [t] [NODE.RMNodeStarter.addNodeToResourceManager] Node pnp://precision:56154/local-extra_2 added.
[2016-03-03 18:45:13,401 INFO ] [t] [NODE.RMNodeStarter.pingAllNodes] Connected to the resource manager at pnp://precision:1199/
[2016-03-03 18:45:14,772 INFO ] [1t1] [NODE.TaskLauncher.doTask] Task started job_prt : t2
[2016-03-03 18:45:14,976 INFO ] [1t2] [NODE.TaskLauncher.doTask] Task started job_prt : t3
[2016-03-03 18:45:15,101 INFO ] [1t1] [NODE.TaskProActiveDataspaces.initDataSpaces] Configuring dataspaces for app 1 on local-extra_2
[2016-03-03 18:45:15,198 INFO ] [1t2] [NODE.TaskProActiveDataspaces.initDataSpaces] Configuring dataspaces for app 1 on local-extra_1
[2016-03-03 18:45:15,226 INFO ] [1t3] [NODE.TaskLauncher.doTask] Task started job_prt : t4
[2016-03-03 18:45:15,292 INFO ] [1t3] [NODE.TaskProActiveDataspaces.initDataSpaces] Configuring dataspaces for app 1 on local-extra_0
[2016-03-03 18:45:15,446 INFO ] [1t2] [NODE.TaskProActiveDataspaces.initDataSpaces] SCRATCH space is file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM372483374/local-extra_1/1/2066328208
[2016-03-03 18:45:15,506 INFO ] [1t1] [NODE.TaskProActiveDataspaces.initDataSpaces] SCRATCH space is file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM372483374/local-extra_2/1/2066328207
[2016-03-03 18:45:15,716 INFO ] [1t3] [NODE.TaskProActiveDataspaces.initDataSpaces] SCRATCH space is file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM372483374/local-extra_0/1/2066328209
[2016-03-03 18:45:15,801 INFO ] [1t1] [NODE.TaskLauncher.kill] Kill received for task
[2016-03-03 18:45:15,820 WARN ] [1t1] [NODE.TaskProActiveDataspaces.initDataSpace] INPUT space is disabled
org.objectweb.proactive.extensions.dataspaces.exceptions.FileSystemException: An error occurred while trying to mount default
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.mountFirstAvailableFileSystem(VFSSpacesMountManagerImpl.java:332)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.ensureVirtualSpaceIsMounted(VFSSpacesMountManagerImpl.java:269)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:168)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:138)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveInputOutput(DataSpacesImpl.java:213)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveDefaultInputOutput(DataSpacesImpl.java:173)
	at org.objectweb.proactive.extensions.dataspaces.api.PADataSpaces.resolveDefaultInput(PADataSpaces.java:181)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:154)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:151)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpace(TaskProActiveDataspaces.java:183)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:151)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:82)
	at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:53)
	at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
	at org.objectweb.proactive.Service.fifoServing(Service.java:146)
	at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Interruption occurred when trying to mount [file:/H:/Users/fviale/workspace/fork/scheduling/data/defaultinput/demo, pappnp://precision:1199/DefaultInputSpace?proactive_vfs_provider_path=/demo]".
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper.mountAny(VFSMountManagerHelper.java:213)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.mountFirstAvailableFileSystem(VFSSpacesMountManagerImpl.java:304)
	... 29 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ExecutorCompletionService.take(ExecutorCompletionService.java:193)
	at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:188)
	at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:215)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper.mountAny(VFSMountManagerHelper.java:208)
	... 30 more
[2016-03-03 18:45:15,982 INFO ] [1t3] [NODE.TaskLauncher.doTask] Task working dir: H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_0\1\2066328209
[2016-03-03 18:45:15,982 INFO ] [1t1] [NODE.TaskLauncher.doTask] Task working dir: H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_2\1\2066328207
[2016-03-03 18:45:15,982 INFO ] [1t2] [NODE.TaskLauncher.doTask] Task working dir: H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_1\1\2066328208
[2016-03-03 18:45:15,983 INFO ] [1t1] [NODE.TaskLauncher.doTask] Input space: 
[2016-03-03 18:45:15,982 INFO ] [1t3] [NODE.TaskLauncher.doTask] Input space: H:\Users\fviale\workspace\fork\scheduling\data\defaultinput\demo
[2016-03-03 18:45:15,983 INFO ] [1t1] [NODE.TaskLauncher.doTask] Output space: H:\Users\fviale\workspace\fork\scheduling\data\defaultoutput\demo
[2016-03-03 18:45:15,983 INFO ] [1t2] [NODE.TaskLauncher.doTask] Input space: H:\Users\fviale\workspace\fork\scheduling\data\defaultinput\demo
[2016-03-03 18:45:15,983 INFO ] [1t1] [NODE.TaskLauncher.doTask] User space: H:\Users\fviale\workspace\fork\scheduling\data\defaultuser\demo
[2016-03-03 18:45:15,983 INFO ] [1t3] [NODE.TaskLauncher.doTask] Output space: H:\Users\fviale\workspace\fork\scheduling\data\defaultoutput\demo
[2016-03-03 18:45:15,983 INFO ] [1t1] [NODE.TaskLauncher.doTask] Global space: H:\Users\fviale\workspace\fork\scheduling\data\defaultglobal
[2016-03-03 18:45:15,983 INFO ] [1t2] [NODE.TaskLauncher.doTask] Output space: H:\Users\fviale\workspace\fork\scheduling\data\defaultoutput\demo
[2016-03-03 18:45:15,983 INFO ] [1t3] [NODE.TaskLauncher.doTask] User space: H:\Users\fviale\workspace\fork\scheduling\data\defaultuser\demo
[2016-03-03 18:45:15,983 INFO ] [1t2] [NODE.TaskLauncher.doTask] User space: H:\Users\fviale\workspace\fork\scheduling\data\defaultuser\demo
[2016-03-03 18:45:15,983 INFO ] [1t3] [NODE.TaskLauncher.doTask] Global space: H:\Users\fviale\workspace\fork\scheduling\data\defaultglobal
[2016-03-03 18:45:15,984 INFO ] [1t2] [NODE.TaskLauncher.doTask] Global space: H:\Users\fviale\workspace\fork\scheduling\data\defaultglobal
[2016-03-03 18:45:15,985 WARN ] [1t1] [NODE.TaskProActiveDataspaces.displayDataspacesStatus] [DATASPACES-WARNING] INPUT space is disabled
[DATASPACES-WARNING] org.objectweb.proactive.extensions.dataspaces.exceptions.FileSystemException: An error occurred while trying to mount default
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.mountFirstAvailableFileSystem(VFSSpacesMountManagerImpl.java:332)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.ensureVirtualSpaceIsMounted(VFSSpacesMountManagerImpl.java:269)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:168)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:138)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveInputOutput(DataSpacesImpl.java:213)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveDefaultInputOutput(DataSpacesImpl.java:173)
	at org.objectweb.proactive.extensions.dataspaces.api.PADataSpaces.resolveDefaultInput(PADataSpaces.java:181)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:154)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:151)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpace(TaskProActiveDataspaces.java:183)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:151)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:82)
	at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:53)
	at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
	at org.objectweb.proactive.Service.fifoServing(Service.java:146)
	at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Interruption occurred when trying to mount [file:/H:/Users/fviale/workspace/fork/scheduling/data/defaultinput/demo, pappnp://precision:1199/DefaultInputSpace?proactive_vfs_provider_path=/demo]".
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper.mountAny(VFSMountManagerHelper.java:213)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.mountFirstAvailableFileSystem(VFSSpacesMountManagerImpl.java:304)
	... 29 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ExecutorCompletionService.take(ExecutorCompletionService.java:193)
	at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:188)
	at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:215)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper.mountAny(VFSMountManagerHelper.java:208)
	... 30 more

[2016-03-03 18:45:16,749 INFO ] [1t0] [NODE.TaskLauncher.doTask] Task started job_prt : t1
[2016-03-03 18:45:16,760 INFO ] [1t0] [NODE.TaskProActiveDataspaces.initDataSpaces] Configuring dataspaces for app 1 on local-extra_2
[2016-03-03 18:45:16,766 WARN ] [1t1] [NODE.ProgressFileReader$ProgressFileReaderThread.run] java.nio.file.NoSuchFileException: H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_2\1\2066328207\.tasks-progress\job-1-task-1-81dc0f7e-d729-46c3-939f-f79e9d890a79.progress
[2016-03-03 18:45:16,769 ERROR] [1t0] [NODE.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>] Could not create directory for application scratch space
org.apache.commons.vfs2.FileSystemException: Could not delete "file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM372483374/local-extra_2/1/2066328207/TaskLogs-1-1.log".
	at org.apache.commons.vfs2.provider.AbstractFileObject.deleteSelf(AbstractFileObject.java:848)
	at org.apache.commons.vfs2.provider.AbstractFileObject.delete(AbstractFileObject.java:907)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.createEmptyDirectoryRelative(VFSNodeScratchSpaceImpl.java:302)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.access$300(VFSNodeScratchSpaceImpl.java:70)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>(VFSNodeScratchSpaceImpl.java:100)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>(VFSNodeScratchSpaceImpl.java:86)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.initForApplication(VFSNodeScratchSpaceImpl.java:256)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator$NodeApplicationConfigurator.configure(NodeConfigurator.java:374)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator$NodeApplicationConfigurator.access$100(NodeConfigurator.java:357)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator.configureApplication(NodeConfigurator.java:197)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesNodes.configureApplication(DataSpacesNodes.java:215)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:143)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:82)
	at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:53)
	at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
	at org.objectweb.proactive.Service.fifoServing(Service.java:146)
	at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not delete "H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_2\1\2066328207\TaskLogs-1-1.log".
	at org.apache.commons.vfs2.provider.local.LocalFile.doDelete(LocalFile.java:126)
	at org.apache.commons.vfs2.provider.AbstractFileObject.deleteSelf(AbstractFileObject.java:837)
	... 30 more
[2016-03-03 18:45:16,771 INFO ] [1t0] [NODE.TaskLauncher.doTask] Failed to execute task
org.objectweb.proactive.extensions.dataspaces.exceptions.FileSystemException: 
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>(VFSNodeScratchSpaceImpl.java:104)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>(VFSNodeScratchSpaceImpl.java:86)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.initForApplication(VFSNodeScratchSpaceImpl.java:256)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator$NodeApplicationConfigurator.configure(NodeConfigurator.java:374)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator$NodeApplicationConfigurator.access$100(NodeConfigurator.java:357)
	at org.objectweb.proactive.extensions.dataspaces.core.NodeConfigurator.configureApplication(NodeConfigurator.java:197)
	at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesNodes.configureApplication(DataSpacesNodes.java:215)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:143)
	at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:82)
	at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:53)
	at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
	at org.objectweb.proactive.Service.fifoServing(Service.java:146)
	at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not delete "file:///H:/Users/fviale/AppData/Local/Temp/PA_JVM372483374/local-extra_2/1/2066328207/TaskLogs-1-1.log".
	at org.apache.commons.vfs2.provider.AbstractFileObject.deleteSelf(AbstractFileObject.java:848)
	at org.apache.commons.vfs2.provider.AbstractFileObject.delete(AbstractFileObject.java:907)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.createEmptyDirectoryRelative(VFSNodeScratchSpaceImpl.java:302)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl.access$300(VFSNodeScratchSpaceImpl.java:70)
	at org.objectweb.proactive.extensions.dataspaces.vfs.VFSNodeScratchSpaceImpl$AppScratchSpaceImpl.<init>(VFSNodeScratchSpaceImpl.java:100)
	... 26 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not delete "H:\Users\fviale\AppData\Local\Temp\PA_JVM372483374\local-extra_2\1\2066328207\TaskLogs-1-1.log".
	at org.apache.commons.vfs2.provider.local.LocalFile.doDelete(LocalFile.java:126)
	at org.apache.commons.vfs2.provider.AbstractFileObject.deleteSelf(AbstractFileObject.java:837)
	... 30 more
```

**Comment by fviale** [comment]
fixed by commit 7b37eec
