### ISSUE TITLE
NPE in VariableSubstitutor when a script has a null parameter

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2497]
When a job is submitted which contains a script (can be selection, fork, task, etc) which has a parameter set to null, the following error occurs:
```

java.lang.NullPointerException
    at org.ow2.proactive.scheduler.common.util.VariableSubstitutor.filterAndUpdate(VariableSubstitutor.java:113)
    at org.ow2.proactive.scheduler.core.SchedulingMethodImpl.resolveScriptVariables(SchedulingMethodImpl.java:519)
    at org.ow2.proactive.scheduler.core.SchedulingMethodImpl.getRMNodes(SchedulingMethodImpl.java:375)
    at org.ow2.proactive.scheduler.core.SchedulingMethodImpl.schedule(SchedulingMethodImpl.java:204)
    at org.ow2.proactive.scheduler.core.SchedulingThread.run(SchedulingThread.java:32)
```

**Comment by fviale** [comment]
fixed by 	2c147a7
