### ISSUE TITLE
Large Objects may not be used in auto-commit mode...

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2524]
Using PWS 7.7.0 with Scheduler and RM configured to use Postgres 9.4 as database, when a Job is submitted, I get the following exception:

```
[2016-04-20 14:51:11,836 WARN   o.o.p.s.c.d.TransactionHelper] DB operation failed
org.ow2.proactive.db.DatabaseManagerException: org.hibernate.HibernateException: org.postgresql.util.PSQLException: Les Large Objects ne devraient pas être utilisés en mode auto-commit.
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.loadExecutableContainer(SchedulerDBManager.java:1639)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.access$900(SchedulerDBManager.java:77)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$37.executeWork(SchedulerDBManager.java:1657)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$37.executeWork(SchedulerDBManager.java:1654)
	at org.ow2.proactive.scheduler.core.db.TransactionHelper.runWithoutTransaction(TransactionHelper.java:95)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.runWithoutTransaction(SchedulerDBManager.java:1691)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.loadExecutableContainer(SchedulerDBManager.java:1654)
	at org.ow2.proactive.scheduler.core.SchedulingMethodImpl.loadAndInit(SchedulingMethodImpl.java:423)
	at org.ow2.proactive.scheduler.core.SchedulingMethodImpl.schedule(SchedulingMethodImpl.java:216)
	at org.ow2.proactive.scheduler.core.SchedulingThread.run(SchedulingThread.java:32)
Caused by: org.hibernate.HibernateException: org.postgresql.util.PSQLException: Les Large Objects ne devraient pas être utilisés en mode auto-commit.
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.wrap(SerializableTypeDescriptor.java:140)
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.wrap(SerializableTypeDescriptor.java:44)
	at org.hibernate.type.descriptor.sql.BlobTypeDescriptor$1.doExtract(BlobTypeDescriptor.java:65)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:64)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:267)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:263)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:338)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2969)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1696)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1628)
	at org.hibernate.loader.Loader.getRow(Loader.java:1515)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:726)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:953)
	at org.hibernate.loader.Loader.doQuery(Loader.java:921)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	at org.hibernate.loader.Loader.doList(Loader.java:2554)
	at org.hibernate.loader.Loader.doList(Loader.java:2540)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	at org.hibernate.loader.Loader.list(Loader.java:2365)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at org.hibernate.internal.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:966)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.queryScriptTaskData(SchedulerDBManager.java:1650)
	at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.loadExecutableContainer(SchedulerDBManager.java:1624)
	... 9 more
Caused by: org.postgresql.util.PSQLException: Les Large Objects ne devraient pas être utilisés en mode auto-commit.
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:265)
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:251)
	at org.postgresql.jdbc.AbstractBlobClob.getLo(AbstractBlobClob.java:283)
	at org.postgresql.jdbc.AbstractBlobClob.getBinaryStream(AbstractBlobClob.java:127)
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.wrap(SerializableTypeDescriptor.java:137)
	... 36 more
```

**Comment by lpellegr** [comment]
Adding property `hibernate.hikari.autoCommit=false` in database configurations (RM and Scheduler) files seems to solve the issue.

**Comment by lpellegr** [comment]
It looks like a more correct way to fix the issue is to use transactions for Hibernate queries that fetch large objects, even if these queries are used to read data only.
