### ISSUE TITLE
Python script task fails to execute

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2547]
When executing a python script, the following error occurs.

		

	
	
```
[139t0@trydev.activeeon.com;10:42:31] Failed to execute task: SyntaxError: mismatched input ' ' expecting EOF in SimpleScript at line number 3 at column number 20 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:202) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[139t0@trydev.activeeon.com;10:42:31] Caused by: org.ow2.proactive.scripting.ScriptException: SyntaxError: mismatched input ' ' expecting EOF in SimpleScript at line number 3 at column number 20 
[139t0@trydev.activeeon.com;10:42:31] at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:190) 
[139t0@trydev.activeeon.com;10:42:31] at org.python.jsr223.PyScriptEngine.compileScript(PyScriptEngine.java:88) 
[139t0@trydev.activeeon.com;10:42:31] at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:47) 
[139t0@trydev.activeeon.com;10:42:31] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scripting.Script.execute(Script.java:319) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[139t0@trydev.activeeon.com;10:42:31] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198) 
[139t0@trydev.activeeon.com;10:42:31] ... 3 more 
```

**Comment by marcocast** [comment]
Problem is in the studio after this commit : https://github.com/ow2-proactive/studio/commit/35d1dd3132ce73468a10e515eff9630e599379b0

The formatting (adding extra spaces) of the CDATA prevents python to work correctly.

**Comment by marcocast** [comment]
Pull request https://github.com/ow2-proactive/studio/pull/255

**Comment by lpellegr** [comment]
@marcocast Please think to close an issue when it is fixed. You can also put a message in your commit or pull-request to close it automatically:

https://help.github.com/articles/closing-issues-via-commit-messages/
