### ISSUE TITLE
When trying to add a custom fork environment system variable in RunAsMe mode a NotImplementedException occurs

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2589]
```
org.ow2.proactive.scheduler.task.exceptions.ForkedJvmProcessException: Failed to execute task in a forked JVM
    at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.createTaskResult(ForkedTaskExecutor.java:139)
    at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.execute(ForkedTaskExecutor.java:122)
    at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.objectweb.proactive.extensions.processbuilder.exception.NotImplementedException: The environment modification of a user process is not implemented
    at org.objectweb.proactive.extensions.processbuilder.LinuxProcessBuilder.environment(LinuxProcessBuilder.java:258)
    at org.ow2.proactive.scheduler.task.executors.ForkedProcessBuilderCreator.executeForkEnvironmentScriptAndExtractVariables(ForkedProcessBuilderCreator.java:106)
    at org.ow2.proactive.scheduler.task.executors.ForkedProcessBuilderCreator.createForkedProcessBuilder(ForkedProcessBuilderCreator.java:77)
    at org.ow2.proactive.scheduler.task.executors.ForkedTaskExecutor.execute(ForkedTaskExecutor.java:83)
    ... 17 more
```

This is a ProActive programming bug, but I raise the issue here for clarity. The exception is explicitely thrown by the LinuxProcessBuilder, instead of delegating the environment change to the Java ProcessBuilder.

This behavior is understandable as, depending on the impersonation strategy, the ProcessBuilder context can be lost during the impersonation.

A possible fix could be to write down into a file the content of the required environment and load this file into the forked process environment, after the impersonation is performed.

**Comment by fviale** [comment]
fixed by commit: https://github.com/ow2-proactive/programming/pull/1327/commits/86977828ab50581151171d3e9d015ff68d3bff5e
