### ISSUE TITLE
Database exceptions when starting the scheduler

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2622]
Multiple exceptions such as this one occur when starting the scheduler:
```
[2016-08-01 14:35:44,024 WARN ] GenerationTarget encountered exception accepting command : Unable to execute command [drop sequence ALIVE_ID_SEQUENCE]
org.hibernate.tool.schema.spi.CommandAcceptanceException: Unable to execute command [drop sequence ALIVE_ID_SEQUENCE]
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:63)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:370)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:355)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:245)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:153)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:125)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:111)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:137)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:64)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:458)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:465)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:724)
	at org.ow2.proactive.resourcemanager.db.RMDBManager.<init>(RMDBManager.java:158)
	at org.ow2.proactive.resourcemanager.db.RMDBManager.createUsingProperties(RMDBManager.java:118)
	at org.ow2.proactive.resourcemanager.db.RMDBManager.access$000(RMDBManager.java:65)
	at org.ow2.proactive.resourcemanager.db.RMDBManager$LazyHolder.<clinit>(RMDBManager.java:77)
	at org.ow2.proactive.resourcemanager.db.RMDBManager.getInstance(RMDBManager.java:84)
	at org.ow2.proactive.resourcemanager.core.account.RMAccountsManager.<init>(RMAccountsManager.java:68)
	at org.ow2.proactive.resourcemanager.core.RMCore.<init>(RMCore.java:254)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.objectweb.proactive.core.mop.ConstructorCallImpl.execute(ConstructorCallImpl.java:136)
	at org.objectweb.proactive.core.body.ActiveBody.<init>(ActiveBody.java:105)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.objectweb.proactive.core.mop.ConstructorCallImpl.execute(ConstructorCallImpl.java:136)
	at org.objectweb.proactive.core.runtime.ProActiveRuntimeImpl.createBody(ProActiveRuntimeImpl.java:883)
	at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.createLocalBody(UniversalBodyProxy.java:245)
	at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.<init>(UniversalBodyProxy.java:160)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.objectweb.proactive.core.mop.MOP.createProxyObject(MOP.java:860)
	at org.objectweb.proactive.core.mop.MOP.newInstance(MOP.java:280)
	at org.objectweb.proactive.core.mop.MOP.newInstance(MOP.java:184)
	at org.objectweb.proactive.core.mop.MOP.createStubObject(MOP.java:1179)
	at org.objectweb.proactive.core.mop.MOP.createStubObject(MOP.java:1172)
	at org.objectweb.proactive.api.PAActiveObject.newActive(PAActiveObject.java:444)
	at org.objectweb.proactive.api.PAActiveObject.newActive(PAActiveObject.java:218)
	at org.ow2.proactive.resourcemanager.RMFactory.startLocal(RMFactory.java:112)
	at org.ow2.proactive.resourcemanager.RMFactory.startLocal(RMFactory.java:188)
	at functionaltests.utils.SchedulerStartForFunctionalTest$1.run(SchedulerStartForFunctionalTest.java:112)
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: ALIVE_ID_SEQUENCE in statement [drop sequence ALIVE_ID_SEQUENCE]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:51)
	... 47 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: ALIVE_ID_SEQUENCE
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 52 more
```

**Comment by fviale** [comment]
Changed the issue to improvement as it is not really a bug (the behavior is expected as the database must be created, but maybe these exceptions could be hidden)
