### ISSUE TITLE
VFS S3 configuration problem prevents rest-client dataspace API from working

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2654]
The following exceptions appears in the scheduling build:

[2016-09-08 07:55:40,786 ERROR      o.o.p.d.RestDataspaceImpl] Cannot create folder for file:/home/activeeon/jenkins/workspace/scheduling/jdk/JDK8/label/Linux/data/defaultuser/admin/root_2016-09-08_07.55.40.734/input in user
org.apache.commons.vfs2.FileSystemException: Could not create a file system manager of class "org.apache.commons.vfs2.impl.StandardFileSystemManager".
	at org.apache.commons.vfs2.VFS.createManager(VFS.java:89)
	at org.apache.commons.vfs2.VFS.getManager(VFS.java:52)
	at org.ow2.proactive_grid_cloud_portal.dataspace.FileSystem$Builder.create(FileSystem.java:214)
	at org.ow2.proactive_grid_cloud_portal.dataspace.RestDataspaceImpl.fileSystem(RestDataspaceImpl.java:456)
	at org.ow2.proactive_grid_cloud_portal.dataspace.RestDataspaceImpl.resolveFile(RestDataspaceImpl.java:405)
	at org.ow2.proactive_grid_cloud_portal.dataspace.RestDataspaceImpl.create(RestDataspaceImpl.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not load VFS configuration from "jar:file:/root/.gradle/caches/modules-2/files-2.1/com.github/vfs-s3/2.4.0/7950963ebf7a3ece7989509b034f26a1bb93302d/vfs-s3-2.4.0.jar!/META-INF/vfs-providers.xml".
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.configure(StandardFileSystemManager.java:192)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.configurePlugins(StandardFileSystemManager.java:146)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.init(StandardFileSystemManager.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.vfs2.VFS.createManager(VFS.java:76)
	... 38 more
Caused by: org.apache.commons.vfs2.FileSystemException: Multiple providers registered for URL scheme "s3".
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.addProvider(DefaultFileSystemManager.java:208)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.addProvider(StandardFileSystemManager.java:372)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.configure(StandardFileSystemManager.java:266)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.configure(StandardFileSystemManager.java:188)
	... 45 more

**Comment by paraita** [comment]
I had this issue with the latest releases when we started integrating that vfs-s3 library in the programming project. My issue was that the emailnotification project was getting and extra file during the release process that was also declaring a S3 provider. If you `./gradlew jar` the emailnotification project, you won't have that extra file, but if you generate the whole release from the release project. The generated emailnotification jar will have the following file that redeclare an S3 provider: META-INF/vfs-providers.xml.
One solution, as @lpellegr proposed, is to exclude that vfs-s3 module from the dependencies of programming.

**Comment by marcocast** [comment]
Multiple providers registered for URL scheme "s3". happens when there are 2 vfs-s3 jars in the same classPath. Why they are 2 no idea yet....
