### ISSUE TITLE
proactive-client fails when creating ssh2 infrastructures with no sshPrivateKey or sshOptions

### ISSUE THREAD

**Issue by marcocast** [ow2-proactive/scheduling#2660]
The following fails because '' is not accepted as no file parameter : 
`bin/proactive-client -createns outer --infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2 hosts.txt 60000 5 22 ssh_user ssh_password '' '' java /Users/mcastigliego/activeeon/releases/7.18.0/ProActiveWorkflowsScheduling-macosx-x64-7.18.0-20160914-0742-SNAPSHOT Linux '' -policy org.ow2.proactive.resourcemanager.nodesource.policy.StaticPolicy 'ALL' 'ALL' -X`
An error occurred.
Stack trace: org.ow2.proactive_grid_cloud_portal.cli.CLIException
    at org.ow2.proactive_grid_cloud_portal.cli.utils.FileUtility.readFileToString(FileUtility.java:80)
    at org.ow2.proactive_grid_cloud_portal.cli.cmd.rm.SetInfrastructureCommand.execute(SetInfrastructureCommand.java:123)
    at org.ow2.proactive_grid_cloud_portal.cli.EntryPoint.executeCommandList(EntryPoint.java:193)
    at org.ow2.proactive_grid_cloud_portal.cli.EntryPoint.run(EntryPoint.java:118)
    at org.ow2.proactive_grid_cloud_portal.cli.CommonEntryPoint.main(CommonEntryPoint.java:51)
Caused by: java.io.FileNotFoundException: File '' does not exist
    at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
    at org.ow2.proactive_grid_cloud_portal.cli.utils.FileUtility.readFileToString(FileUtility.java:78)
    ... 4 more

In order to make it work an empty file called "file" as been created  : 
`
bin/proactive-client -createns outer --infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2 hosts.txt 60000 5 22 ssh_user ssh_password 'file' 'file' java /Users/mcastigliego/activeeon/releases/7.18.0/ProActiveWorkflowsScheduling-macosx-x64-7.18.0-20160914-0742-SNAPSHOT Linux '' -policy org.ow2.proactive.resourcemanager.nodesource.policy.StaticPolicy 'ALL' 'ALL' -X`
Node source successfully created.

**Comment by fviale** [comment]
Very annoying issue.

**Comment by marcocast** [comment]
agree. it forces us to create empty files as a workaround
