### ISSUE TITLE
java.lang.InternalError: Unexpected CryptoAPI failure generating seed 

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2750]
Saw this unexpected error occurring (Windows, RunAsMe mode)
```
java.lang.InternalError: Unexpected CryptoAPI failure generating seed
	at sun.security.provider.NativeSeedGenerator.getSeedBytes(NativeSeedGenerator.java:62)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:203)
	at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:221)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
	at java.security.SecureRandom.next(SecureRandom.java:491)
	at java.util.Random.nextLong(Random.java:424)
	at java.io.File$TempDirectory.generateFile(File.java:1905)
	at java.io.File.createTempFile(File.java:2010)
	at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.writeNodesFile(InProcessTaskExecutor.java:99)
	at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:129)
	at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:107)
	at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:97)
```

**Comment by lpellegr** [comment]
@fviale Is it after applying some changes as we discussed briefly this morning? if yes please freeze your code in a branch and reference this branch in this issue. It will help reproducing the problem when someone will work on the issue. Also, explaining the steps to get the problem or attaching a Workflow example would be really convenient.

**Comment by fviale** [comment]
After latest changes in processbuilder/windows code, the problem did not reappear.

**Comment by ladhadeepak** [comment]
Hi @fviale, @lpellegr, We are seeing the same issue on Windows. Can you please share the changes you have made to processbuilder/windows code to resolve this issue?
Thanks.

**Comment by fviale** [comment]
hello @ladhadeepak 
This issue is coming directly from the Java Runtime Environment used and not from the ProActive scheduling code.

ProActive uses a Java 8 version. Could you please retry with a recent Java 8 maintenance build ?

For example, you can try with the latest provided by Adoptium:
https://adoptium.net/temurin/releases?version=8

**Comment by fviale** [comment]
@ladhadeepak additionnally, we do not use java.io.File.createTempFile in the org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.writeNodesFile method any more. So the issue you mention cannot be triggerred from the same context in more recent ProActive versions.

**Comment by ladhadeepak** [comment]
Thanks @fviale for quick response.
My bad, I missed mentioning that we use bouncycastle. We are seeing the following issue -

>: java.lang.InternalError: Unexpected CryptoAPI failure generating seed
              at sun.security.provider.NativeSeedGenerator.getSeedBytes(NativeSeedGenerator.java:62)
              at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
              at sun.security.provider.SecureRandom.engineGenerateSeed(SecureRandom.java:139)
              at java.security.SecureRandom.generateSeed(SecureRandom.java:533)
              at org.bouncycastle.crypto.util.BasicEntropySourceProvider$1.getEntropy(Unknown Source)
              at org.bouncycastle.crypto.fips.ContinuousTestingEntropySource.getEntropy(Unknown Source)
              at org.bouncycastle.crypto.fips.HashSP800DRBG.getEntropy(Unknown Source)
              at org.bouncycastle.crypto.fips.HashSP800DRBG.reseed(Unknown Source)
              at org.bouncycastle.crypto.fips.HashSP800DRBG.generate(Unknown Source)
              at org.bouncycastle.crypto.fips.ContinuousTestingPseudoRNG.generate(Unknown Source)
              at org.bouncycastle.crypto.fips.DRBGPseudoRandom.generate(Unknown Source)
              at org.bouncycastle.crypto.fips.FipsSecureRandom$RandomSpi.engineNextBytes(Unknown Source)
              at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
              at org.bouncycastle.jcajce.provider.ProvRandom$1$1.engineNextBytes(Unknown Source)
              at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
              at java.security.SecureRandom.next(SecureRandom.java:491)
              at java.util.Random.nextLong(Random.java:424)
              ...

**Comment by fviale** [comment]
@ladhadeepak 
In this stack trace I don't see any ProActive code context. I need more context in order to understand.

**Comment by ladhadeepak** [comment]
@fviale it's not in ProActive context. We don't use ProActive. 
We use Bouncy Castle Crypto package to be FIPS 140-2 compliant.

**Comment by fviale** [comment]
well, in that case, you should file the issue in the bouncy castle issue tracker ...

**Comment by ladhadeepak** [comment]
Sure, thanks for the input.

**Comment by fviale** [comment]
in addition, you might get some information in:
https://serverfault.com/questions/899158/what-is-the-dev-urandom-equivalent-on-windows-jvm-level

The issue you face could be an entropy-related issue. Otherwise, it is most likely a concurrent type of issue (generating seeds in parallel)
