### ISSUE TITLE
Creating nodesources with the same name gives 504 and no meaningful error message

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/scheduling#2814]
Create two nodesources which have the same name violates the constrain that nodesources must have unique names. 

Creating a nodesource with a duplicate name gives a 504 Gateway Timeout without telling the user what happened. 

In the logs one can find this (I think that is not understandable for users):

Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constrai
nt violation: unique constraint or index violation; SYS_PK_10127 table: NODESOUR
CEDATA
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(Prepared
StatementProxy.java:61)
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate
(PreparedStatementJavassistProxy.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(
ResultSetReturnImpl.java:204)
        ... 38 more

**Comment by fviale** [comment]
Addressed by #3035
