### ISSUE TITLE
Client class is stored in rm db NodeSourceData with a non-constant serialuid

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2851]
When loading an older version of the resource manager database, the following error occurs:

```
[2017-04-26 17:15:00,065 38/RM_NODE ERROR                         p.body] Exception occurred in runActivity method of body Body for ActiveObject_org.ow2.proactive.resourcemanager.core.RMCore node=pnp://10.21.80.162:64738/RM_NODE id=ActiveObject_org.ow2.proactive.resourcemanager.core.RMCore_-18a0eb5e-15bacc1a20f--7fff--e6660f67f1e318d1--18a0eb5e-15bacc1a20f--8000. Now terminating the body
org.ow2.proactive.db.DatabaseManagerException: org.hibernate.type.SerializationException: could not deserialize
    at org.ow2.proactive.db.TransactionHelper.tryExecuteTransactionLoop(TransactionHelper.java:111)
    at org.ow2.proactive.db.TransactionHelper.executeReadOnlyTransaction(TransactionHelper.java:60)
    at org.ow2.proactive.resourcemanager.db.RMDBManager.executeReadTransaction(RMDBManager.java:248)
    at org.ow2.proactive.resourcemanager.db.RMDBManager.getNodeSources(RMDBManager.java:303)
    at org.ow2.proactive.resourcemanager.core.RMCore.restoreNodeSources(RMCore.java:436)
    at org.ow2.proactive.resourcemanager.core.RMCore.initActivity(RMCore.java:399)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:155)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.type.SerializationException: could not deserialize
    at org.hibernate.internal.util.SerializationHelper.doDeserialize(SerializationHelper.java:231)
    at org.hibernate.internal.util.SerializationHelper.deserialize(SerializationHelper.java:287)
    at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.fromBytes(SerializableTypeDescriptor.java:138)
    at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.wrap(SerializableTypeDescriptor.java:120)
    at org.hibernate.type.descriptor.java.SerializableTypeDescriptor.wrap(SerializableTypeDescriptor.java:27)
    at org.hibernate.type.descriptor.sql.BlobTypeDescriptor$1.doExtract(BlobTypeDescriptor.java:48)
    at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:235)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:231)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:222)
    at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:296)
    at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2762)
    at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1728)
    at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1654)
    at org.hibernate.loader.Loader.getRow(Loader.java:1543)
    at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:727)
    at org.hibernate.loader.Loader.processResultSet(Loader.java:972)
    at org.hibernate.loader.Loader.doQuery(Loader.java:930)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
    at org.hibernate.loader.Loader.doList(Loader.java:2610)
    at org.hibernate.loader.Loader.doList(Loader.java:2593)
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
    at org.hibernate.loader.Loader.list(Loader.java:2417)
    at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
    at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1339)
    at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
    at org.ow2.proactive.resourcemanager.db.RMDBManager$7.doInTransaction(RMDBManager.java:308)
    at org.ow2.proactive.resourcemanager.db.RMDBManager$7.doInTransaction(RMDBManager.java:303)
    at org.ow2.proactive.db.TransactionHelper.tryExecuteTransaction(TransactionHelper.java:122)
    at org.ow2.proactive.db.TransactionHelper.tryExecuteTransactionLoop(TransactionHelper.java:96)
    ... 7 more
Caused by: java.io.InvalidClassException: org.ow2.proactive.resourcemanager.authentication.Client; local class incompatible: stream classdesc serialVersionUID = 713, local class serialVersionUID = 726
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at org.hibernate.internal.util.SerializationHelper.doDeserialize(SerializationHelper.java:225)
```

The Client class should have a fixed serial version uid

**Comment by fviale** [comment]
fixed by https://github.com/ow2-proactive/scheduling/commit/0fcb02f9557b60f2581132d2fb4900e574b724f8
