### ISSUE TITLE
Multi-node tasks with cleaning scripts can create a deadlock

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2860]
Attached is a thread dump of a deadlock occurring when executing a cleaning script on a multi-node task.

[jstack.txt](https://github.com/ow2-proactive/scheduling/files/1004222/jstack.txt)

The deadlock is the following:

```
Found one Java-level deadlock:
=============================
"PNP shared thread pool #2-thread-3602":
  waiting to lock monitor 0x00002ad6588b0778 (object 0x00000006c60878e0, a org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject),
  which is held by "InternalOperationsThreadPool #7-thread-3"
"InternalOperationsThreadPool #7-thread-3":
  waiting to lock monitor 0x00000000203649e8 (object 0x000000074c77a170, a org.objectweb.proactive.core.body.future.FutureProxy),
  which is held by "PNP shared thread pool #2-thread-3602"

Java stack information for the threads listed above:
===================================================
"PNP shared thread pool #2-thread-3602":
	at org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject.cleanCallBack(RMProxyActiveObject.java:222)
	- waiting to lock <0x00000006c60878e0> (a org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject)
	at sun.reflect.GeneratedMethodAccessor1237.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:345)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.core.body.request.RequestReceiverImpl.receiveRequest(RequestReceiverImpl.java:161)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveRequest(BodyImpl.java:210)
	at org.objectweb.proactive.core.body.AbstractBody.receiveRequest(AbstractBody.java:221)
	at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:229)
	at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:140)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.sendRequest(BodyImpl.java:742)
	at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:436)
	at org.objectweb.proactive.core.body.future.LocalFutureUpdateCallbacks.run(LocalFutureUpdateCallbacks.java:119)
	at org.objectweb.proactive.core.body.future.FutureProxy.receiveReply(FutureProxy.java:231)
	- locked <0x000000074c77a170> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.core.body.future.FuturePool.receiveFutureValue(FuturePool.java:259)
	- locked <0x00000006c60874b8> (a org.objectweb.proactive.core.body.future.FuturePool)
	at org.objectweb.proactive.core.body.reply.ReplyReceiverImpl.receiveReply(ReplyReceiverImpl.java:37)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveReply(BodyImpl.java:236)
	at org.objectweb.proactive.core.body.AbstractBody.receiveReply(AbstractBody.java:236)
	at sun.reflect.GeneratedMethodAccessor486.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:345)
	at org.objectweb.proactive.core.remoteobject.RemoteObjectImpl.receiveMessage(RemoteObjectImpl.java:87)
	at org.objectweb.proactive.core.remoteobject.InternalRemoteRemoteObjectImpl.receiveMessage(InternalRemoteRemoteObjectImpl.java:132)
	at org.objectweb.proactive.extensions.pnp.PNPROMessageRequest.processMessage(PNPROMessageRequest.java:93)
	at org.objectweb.proactive.extensions.pnp.PNPServerHandler$RequestExecutor.run(PNPServerHandler.java:296)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"InternalOperationsThreadPool #7-thread-3":
	at org.objectweb.proactive.core.body.future.FutureProxy.isAwaited(FutureProxy.java:291)
	- waiting to lock <0x000000074c77a170> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.api.PAFuture.isAwaited(PAFuture.java:135)
	at org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject.cleanCallBack(RMProxyActiveObject.java:226)
	- locked <0x00000006c60878e0> (a org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject)
	at sun.reflect.GeneratedMethodAccessor1237.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:345)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.core.body.request.RequestReceiverImpl.receiveRequest(RequestReceiverImpl.java:161)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveRequest(BodyImpl.java:210)
	at org.objectweb.proactive.core.body.AbstractBody.receiveRequest(AbstractBody.java:221)
	at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:229)
	at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:140)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.sendRequest(BodyImpl.java:742)
	at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:436)
	at org.objectweb.proactive.core.body.future.LocalFutureUpdateCallbacks.run(LocalFutureUpdateCallbacks.java:119)
	at org.objectweb.proactive.core.body.future.FutureProxy.addCallback(FutureProxy.java:633)
	- locked <0x000000074c80dbc0> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.api.PAEventProgramming.addActionOnFuture(PAEventProgramming.java:66)
	at org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject.handleCleaningScript(RMProxyActiveObject.java:197)
	at org.ow2.proactive.scheduler.core.rmproxies.RMProxyActiveObject.releaseNodes(RMProxyActiveObject.java:169)
	at sun.reflect.GeneratedMethodAccessor680.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:345)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.core.body.request.RequestReceiverImpl.receiveRequest(RequestReceiverImpl.java:161)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveRequest(BodyImpl.java:210)
	at org.objectweb.proactive.core.body.AbstractBody.receiveRequest(AbstractBody.java:221)
	at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:229)
	at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:140)
	at org.objectweb.proactive.core.body.HalfBody$HalfLocalBodyStrategy.sendRequest(HalfBody.java:230)
	at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:436)
	at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequestInternal(UniversalBodyProxy.java:424)
	at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:398)
	at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:339)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsOneWay(AbstractBodyProxy.java:227)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.invokeOnBody(AbstractBodyProxy.java:139)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reify(AbstractBodyProxy.java:113)
	at pa.stub.org.ow2.proactive.scheduler.core.rmproxies._StubRMProxyActiveObject.releaseNodes(_StubRMProxyActiveObject.java)
	at org.ow2.proactive.scheduler.core.rmproxies.RMProxy.releaseNodes(RMProxy.java:141)
	at org.ow2.proactive.scheduler.core.TerminationData.handleTermination(TerminationData.java:182)
	at org.ow2.proactive.scheduler.core.SchedulingService$16.run(SchedulingService.java:739)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```

**Comment by marcocast** [comment]
this should be fixed, right?
