### ISSUE TITLE
Scheduler api Bug

### ISSUE THREAD

**Issue by Aminelouati** [ow2-proactive/scheduling#2905]
When we have a loop task in the workflow it is expected that Scheduler api should execute it even in the case of a restart of the server.  

Failed to execute task: NameError: name 'schedulerapi' is not defined in SimpleScript at line number 15
        at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:224)
        at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:157)
        at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:115)
        at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:105)
Caused by: org.ow2.proactive.scripting.ScriptException: NameError: name 'schedulerapi' is not defined in SimpleScript at line number 15
        at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:47)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at org.ow2.proactive.scripting.Script.execute(Script.java:312)
        at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:65)
        at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:220)

**Comment by paraita** [comment]
The binding of `schedulerapi` to the actual java class is done [here](https://github.com/ow2-proactive/scheduling/blob/master/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/executors/forked/env/ForkedTaskVariablesManager.java#L81). We can reproduce a similar issue by running the example schedulerapi code from the documentation directly on a Node console through the RM portal.

**Comment by fviale** [comment]
From the RM portal node console, this is normal, the schedulerapi variable is bound only inside a task execution.

**Comment by fviale** [comment]
fixed by:
https://github.com/ow2-proactive/scheduling/commit/28dd00d7cc3abd8f29132bf74075d909ec08e17f
https://github.com/ow2-proactive/scheduling/commit/5c9a8230856d99b1362f38d418f44f8ef8ea24ab
https://github.com/ow2-proactive/scheduling/commit/d49bed987366cea9247d702461d53f878b12aeb7
