### ISSUE TITLE
DataSpaceAPIs and SchedulerAPI variables bindings are not set in cleaning script

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2925]
When trying to use the dataspace api in a cleaning script, the following error occurs:
```

    at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
    at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
    at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:47)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:312)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
    at org.objectweb.proactive.Service.serve(Service.java:119)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:178)
    at org.objectweb.proactive.Service.fifoServing(Service.java:141)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:329)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
    at java.lang.Thread.run(Thread.java:748)
```
It may be possible and useful to include these bindings in the cleaning script, though not completely trivial (handling of user credentials, for example).

**Comment by fviale** [comment]
fixed by #3030
