### ISSUE TITLE
Accessing '/rest/rm/monitoring' without valid session ID triggers a NPE with error 500.

### ISSUE THREAD

**Issue by vinseon** [ow2-proactive/scheduling#2985]
When we try to access the Resource Manager's REST API without providing a valid session ID, it triggers an NullPointerException and the server returns a 500 error code.
It should instead return a 403 Forbidden error if the session ID is not provided or invalid.

## Example

$ curl -X GET http://localhost:8080/rest/rm/monitoring

```json
{"httpErrorCode":500,"errorMessage":null,"stackTrace":"java.lang.NullPointerException\n","exception":{"cause":null,"stackTrace":[],"message":null,"localizedMessage":null,"suppressed":[]},"exceptionClass":"java.lang.NullPointerException"}
```

Complete stack trace:

```json
{"httpErrorCode":500,"errorMessage":null,"stackTrace":"java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.ow2.proactive_grid_cloud_portal.common.SessionStore.get(SessionStore.java:61)
        at org.ow2.proactive_grid_cloud_portal.rm.RMRest.checkAccess(RMRest.java:117)
        at org.ow2.proactive_grid_cloud_portal.rm.RMRest.getInitialState(RMRest.java:257)
        at sun.reflect.GeneratedMethodAccessor803.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
","exception":{"cause":null,"stackTrace":[{"methodName":"get","fileName":"ConcurrentHashMap.java","lineNumber":936,"className":"java.util.concurrent.ConcurrentHashMap","nativeMethod":false},{"methodName":"get","fileName":"SessionStore.java","lineNumber":61,"className":"org.ow2.proactive_grid_cloud_portal.common.SessionStore","nativeMethod":false},{"methodName":"checkAccess","fileName":"RMRest.java","lineNumber":117,"className":"org.ow2.proactive_grid_cloud_portal.rm.RMRest","nativeMethod":false},{"methodName":"getInitialState","fileName":"RMRest.java","lineNumber":257,"className":"org.ow2.proactive_grid_cloud_portal.rm.RMRest","nativeMethod":false},{"methodName":"invoke","fileName":null,"lineNumber":-1,"className":"sun.reflect.GeneratedMethodAccessor803","nativeMethod":false},{"methodName":"invoke","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43,"className":"sun.reflect.DelegatingMethodAccessorImpl","nativeMethod":false},{"methodName":"invoke","fileName":"Method.java","lineNumber":498,"className":"java.lang.reflect.Method","nativeMethod":false},{"methodName":"invoke","fileName":"MethodInjectorImpl.java","lineNumber":139,"className":"org.jboss.resteasy.core.MethodInjectorImpl","nativeMethod":false},{"methodName":"invokeOnTarget","fileName":"ResourceMethodInvoker.java","lineNumber":295,"className":"org.jboss.resteasy.core.ResourceMethodInvoker","nativeMethod":false},{"methodName":"invoke","fileName":"ResourceMethodInvoker.java","lineNumber":249,"className":"org.jboss.resteasy.core.ResourceMethodInvoker","nativeMethod":false},{"methodName":"invoke","fileName":"ResourceMethodInvoker.java","lineNumber":236,"className":"org.jboss.resteasy.core.ResourceMethodInvoker","nativeMethod":false},{"methodName":"invoke","fileName":"SynchronousDispatcher.java","lineNumber":402,"className":"org.jboss.resteasy.core.SynchronousDispatcher","nativeMethod":false},{"methodName":"invoke","fileName":"SynchronousDispatcher.java","lineNumber":209,"className":"org.jboss.resteasy.core.SynchronousDispatcher","nativeMethod":false},{"methodName":"service","fileName":"ServletContainerDispatcher.java","lineNumber":221,"className":"org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher","nativeMethod":false},{"methodName":"service","fileName":"HttpServletDispatcher.java","lineNumber":56,"className":"org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher","nativeMethod":false},{"methodName":"service","fileName":"HttpServletDispatcher.java","lineNumber":51,"className":"org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher","nativeMethod":false},{"methodName":"service","fileName":"HttpServlet.java","lineNumber":790,"className":"javax.servlet.http.HttpServlet","nativeMethod":false},{"methodName":"handle","fileName":"ServletHolder.java","lineNumber":812,"className":"org.eclipse.jetty.servlet.ServletHolder","nativeMethod":false},{"methodName":"doHandle","fileName":"ServletHandler.java","lineNumber":587,"className":"org.eclipse.jetty.servlet.ServletHandler","nativeMethod":false},{"methodName":"handle","fileName":"ScopedHandler.java","lineNumber":143,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"handle","fileName":"SecurityHandler.java","lineNumber":577,"className":"org.eclipse.jetty.security.SecurityHandler","nativeMethod":false},{"methodName":"doHandle","fileName":"SessionHandler.java","lineNumber":223,"className":"org.eclipse.jetty.server.session.SessionHandler","nativeMethod":false},{"methodName":"doHandle","fileName":"ContextHandler.java","lineNumber":1127,"className":"org.eclipse.jetty.server.handler.ContextHandler","nativeMethod":false},{"methodName":"doScope","fileName":"ServletHandler.java","lineNumber":515,"className":"org.eclipse.jetty.servlet.ServletHandler","nativeMethod":false},{"methodName":"doScope","fileName":"SessionHandler.java","lineNumber":185,"className":"org.eclipse.jetty.server.session.SessionHandler","nativeMethod":false},{"methodName":"doScope","fileName":"ContextHandler.java","lineNumber":1061,"className":"org.eclipse.jetty.server.handler.ContextHandler","nativeMethod":false},{"methodName":"handle","fileName":"ScopedHandler.java","lineNumber":141,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"handle","fileName":"HandlerList.java","lineNumber":52,"className":"org.eclipse.jetty.server.handler.HandlerList","nativeMethod":false},{"methodName":"handle","fileName":"HandlerWrapper.java","lineNumber":97,"className":"org.eclipse.jetty.server.handler.HandlerWrapper","nativeMethod":false},{"methodName":"handle","fileName":"Server.java","lineNumber":499,"className":"org.eclipse.jetty.server.Server","nativeMethod":false},{"methodName":"handle","fileName":"HttpChannel.java","lineNumber":311,"className":"org.eclipse.jetty.server.HttpChannel","nativeMethod":false},{"methodName":"onFillable","fileName":"HttpConnection.java","lineNumber":257,"className":"org.eclipse.jetty.server.HttpConnection","nativeMethod":false},{"methodName":"run","fileName":"AbstractConnection.java","lineNumber":544,"className":"org.eclipse.jetty.io.AbstractConnection$2","nativeMethod":false},{"methodName":"runJob","fileName":"QueuedThreadPool.java","lineNumber":635,"className":"org.eclipse.jetty.util.thread.QueuedThreadPool","nativeMethod":false},{"methodName":"run","fileName":"QueuedThreadPool.java","lineNumber":555,"className":"org.eclipse.jetty.util.thread.QueuedThreadPool$3","nativeMethod":false},{"methodName":"run","fileName":"Thread.java","lineNumber":748,"className":"java.lang.Thread","nativeMethod":false}],"message":null,"localizedMessage":null,"suppressed":[]},"exceptionClass":"java.lang.NullPointerException"}
```

## Cause

No verification is performed when retrieving a session from its ID:

https://github.com/ow2-proactive/scheduling/blob/f94a46516953db03cb6c408b4a6051de7c27a2c8/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/common/SessionStore.java#L61

**Comment by Mykhailenko** [comment]
Fixed in 10.0.0.
