### ISSUE TITLE
ProtocolViolation error in WebSocket08FrameDecoder

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#3059]
Errors occur in netty websocket protocol, this implies systematic web socket disconnections between client and server.

The problem can be shown in the following reconnection stack trace:
```
at org.ow2.proactive.scheduler.smartproxy.common.AbstractSmartProxy.syncAwaitedJobs(AbstractSmartProxy.java:411)

                at org.ow2.proactive_grid_cloud_portal.smartproxy.RestSmartProxyImpl.notifyDisconnection(RestSmartProxyImpl.java:665)

                at org.ow2.proactive.scheduler.rest.SchedulerEventReceiver$1.on(SchedulerEventReceiver.java:104)

                at org.atmosphere.wasync.transport.TransportsUtil.matchFunction(TransportsUtil.java:117)

                at org.atmosphere.wasync.transport.TransportsUtil.invokeFunction(TransportsUtil.java:73)

                at org.atmosphere.wasync.transport.WebSocketTransport.close(WebSocketTransport.java:137)

                at org.atmosphere.wasync.transport.WebSocketTransport$TextListener.onClose(WebSocketTransport.java:410)

                at com.ning.http.client.providers.netty.ws.NettyWebSocket.onClose(NettyWebSocket.java:158)

                at com.ning.http.client.providers.netty.ws.NettyWebSocket.close(NettyWebSocket.java:134)

                at com.ning.http.client.providers.netty.handler.WebSocketProtocol.onClose(WebSocketProtocol.java:203)

                at com.ning.http.client.providers.netty.handler.Processor.channelClosed(Processor.java:129)

                at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)

                at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)

                at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:60)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)

                at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)

                at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:570)

                at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371)

                at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)

                at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)

                at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:375)

                at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)

                at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)

                at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)

                at org.jboss.netty.channel.Channels.close(Channels.java:812)

                at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:206)

                at org.jboss.netty.channel.ChannelFutureListener$1.operationComplete(ChannelFutureListener.java:41)

                at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)

                at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)

                at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:387)

                at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:381)

                at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:242)

                at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:71)

                at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)

                at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)

                at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)

                at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)

                at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)

                at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)

                at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)

                at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)

                at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)

                at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)

                at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)

                at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)

                at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

                at java.lang.Thread.run(Thread.java:745)
```
The highlighted line in WebSocket08FrameDecoder is:
protocolViolation(channel, "Max frame length of " + maxFramePayloadLength + " has been exceeded.");

**Comment by fviale** [comment]
After adding log messages when broadcasting events from the server, the problem happens when sending JobState as event. JobState can indeed be very big, and this does not seem to be well supported by websockets.

**Comment by amouhoub** [comment]
@fviale could you please elaborate more on this, how to exactly reproduce it, what is the entry-point for this ? or at least the full stack-trace please

**Comment by mbenguig** [comment]
@fviale Could you please explain how to reproduce this issue ?

**Comment by mbenguig** [comment]
Cannot be reproduced.
