### ISSUE TITLE
Unable to delete scheduled job when using MySQL

### ISSUE THREAD

**Issue by vinseon** [ow2-proactive/scheduling#3080]
When using MySQL 5.7, we are unable to delete a Job from the scheduler portal:
```
Cannot delete or update a parent row: a foreign key constraint fails (`scheduler`.`task_data`, CONSTRAINT `FKaksf61esdr7cp26gvom5osl1s` FOREIGN KEY (`JOB_ID`) REFERENCES `job_data` (`ID`))
```

Here are more details about the issue:
```
[2018-01-09 18:50:37,218 8-thread-2 WARN       o.o.p.d.TransactionHelper] Database operation failed
org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:91)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:60)
        at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:111)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:429)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1361)
        at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:102)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$21.doInTransaction(SchedulerDBManager.java:810)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager$21.doInTransaction(SchedulerDBManager.java:792)
        at org.ow2.proactive.db.TransactionHelper.tryExecuteTransaction(TransactionHelper.java:122)
        at org.ow2.proactive.db.TransactionHelper.tryExecuteTransactionLoop(TransactionHelper.java:96)
        at org.ow2.proactive.db.TransactionHelper.executeReadWriteTransaction(TransactionHelper.java:78)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.executeReadWriteTransaction(SchedulerDBManager.java:1735)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.removeJob(SchedulerDBManager.java:792)
        at org.ow2.proactive.scheduler.core.JobRemoveHandler.call(JobRemoveHandler.java:98)
        at org.ow2.proactive.scheduler.core.JobRemoveHandler.call(JobRemoveHandler.java:44)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`scheduler`.`task_data`, CONSTRAINT `FKaksf61esdr7cp26gvom5osl1s` FOREIGN KEY (`JOB_ID`) REFERENCES `job_data` (`ID`))
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:533)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
        at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
        at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
        at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2034)
        at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:1970)
        at com.mysql.cj.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5001)
        at com.mysql.cj.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1955)
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
        ... 20 more
```

The error is wether due to a missing `@cascade` annotation on the `JobData` entity, or it is directly related to the SQL queries into the [`removeJob()` method](https://github.com/ow2-proactive/scheduling/blame/0935159d04c08586bf2ee8bdbfab9d790a18b2a2/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/SchedulerDBManager.java#L778).

It is worth noting that this only appears with MySQL, both HSQL and PostgreSQL are OK. It definitely require more investigations.

**Comment by vinseon** [comment]
This error is due to the hibernate dialect which must be manually set to InnoDB in order to manage foreign keys and relationship constraints. The correct property is already set in MySQL template.
