### ISSUE TITLE
Running a multinode task with topology selection set and pa.rm.topology.distance.enabled=false causes continuous connection loss between the scheduler and the RM

### ISSUE THREAD

**Issue by gheon** [ow2-proactive/scheduling#3082]
When the pa.rm.topology.distance.enabled is set to false (default), and a user tries to execute a workflow with a  multinode task with topology selection set, the scheduler continuously disconnect/reconnect with the RM with the following exception looping:

```
Unexpected exception in the scheduling thread - checking the connection to resource manager
org.ow2.proactive.resourcemanager.frontend.topology.TopologyDisabledException: Topology distance is disabled, cannot use distance-based descriptors
    at org.ow2.proactive.resourcemanager.selection.topology.TopologyManager.getHandler(TopologyManager.java:124)
    at org.ow2.proactive.resourcemanager.selection.SelectionManager.doSelectNodes(SelectionManager.java:253)
    at org.ow2.proactive.resourcemanager.selection.SelectionManager.selectNodes(SelectionManager.java:214)
    at sun.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
    at org.objectweb.proactive.Service.serve(Service.java:119)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:178)
    at org.objectweb.proactive.Service.fifoServing(Service.java:141)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:329)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
    at java.lang.Thread.run(Thread.java:748)
    [...]
```

This leads to the impossibility of executing any workflow, until eventually the whole server becomes down. 

This exception should be handled better by the SelectionManager and treated as a selection script exception.

**Comment by mbenguig** [comment]
Tested with:
- pa.rm.topology.distance.enabled is set to false
- A single task wkw with a number of nodes = 2 + topology = best proximity (set at the task level)
The task is canceled without exception in the scheduler log. The output is "Topology is disabled"
Not able to reproduce it.
