### ISSUE TITLE
Deadlock between RMCore and NodeSource

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#3222]
The following two active objects are in deadlock:

"RMCore on pnp://precision:64738/RM_NODE" #194 prio=5 os_prio=0 tid=0x0000000021cd3800 nid=0x2f80 in Object.wait() [0x000000002f67d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.objectweb.proactive.core.body.future.FutureProxy.waitFor(FutureProxy.java:339)
	- locked <0x0000000088591f70> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:332)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.invokeOnBody(AbstractBodyProxy.java:159)
	at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reify(AbstractBodyProxy.java:113)
	at pa.stub.org.ow2.proactive.resourcemanager.nodesource._StubNodeSource.removeDeployingNode(_StubNodeSource.java)
	at org.ow2.proactive.resourcemanager.core.RMCore.removeDeployingNode(RMCore.java:2409)
	at org.ow2.proactive.resourcemanager.core.RMCore.removeNode(RMCore.java:908)
	at org.ow2.proactive.resourcemanager.core.RMCore.removeNode(RMCore.java:893)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.Service.serve(Service.java:119)
	at org.ow2.proactive.resourcemanager.core.RMCore.runActivity(RMCore.java:511)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
	at java.lang.Thread.run(Thread.java:748)

"Node Source "LocalDynamic"" #670 prio=5 os_prio=0 tid=0x000000014787b000 nid=0xb24 in Object.wait() [0x000000006cc5e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.objectweb.proactive.core.body.future.FutureProxy.waitFor(FutureProxy.java:339)
	- locked <0x000000008850d828> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.core.body.future.FutureProxy.waitFor(FutureProxy.java:300)
	- locked <0x000000008850d828> (a org.objectweb.proactive.core.body.future.FutureProxy)
	at org.objectweb.proactive.core.body.future.FutureProxy.reify(FutureProxy.java:443)
	at pa.stub.org.objectweb.proactive.core.util.wrapper._StubBooleanWrapper.getBooleanValue(_StubBooleanWrapper.java)
	at org.ow2.proactive.resourcemanager.nodesource.NodeSource.acquireNode(NodeSource.java:432)
	at sun.reflect.GeneratedMethodAccessor621.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.Service.serve(Service.java:119)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:189)
	at org.ow2.proactive.resourcemanager.nodesource.NodeSource.runActivity(NodeSource.java:284)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fviale** [comment]
[stack.log](https://github.com/ow2-proactive/scheduling/files/2018092/stack.log)
