### ISSUE TITLE
RestartDownNodesPolicy does not work for LOST nodes with SSHInfrastructureV2

### ISSUE THREAD

**Issue by jrochas** [ow2-proactive/scheduling#3322]
When an SSHInfrastructureV2 is deployed with a RestartDownNodesPolicy, nodes that are LOST are detected by the policy but when trying to reacquire, 0 nodes are asked to be acquired. The consequence is that the LOST nodes are removed, but no other node is ever added, resulting in a compete loss of the nodes.

This is the case in the current SNAPSHOT, but also apparently in 7.28

**Comment by jrochas** [comment]
`[2018-09-12 16:44:48,523 -thread-17 WARN  .p.r.n.i.InfrastructureManager] Declaring node as lost: deploying://cccccccc/cccccccc__localhost__22_1, unable to deploy on localhost/127.0.0.1                          
com.jcraft.jsch.JSchException: Auth fail                                                                                                                                                                           
        at com.jcraft.jsch.Session.connect(Session.java:519)                                                                                                                                                       
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2.startNodeImpl(SSHInfrastructureV2.java:246)                                                                             
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.HostsFileBasedInfrastructureManager.startNodeImplWithRetries(HostsFileBasedInfrastructureManager.java:307)                                  
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.HostsFileBasedInfrastructureManager$1.run(HostsFileBasedInfrastructureManager.java:213)                                                     
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                         
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                         
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                                                   
                                                                                                                                                                                                                   
[2018-09-12 16:44:48,524 -thread-17 WARN  FileBasedInfrastructureManager] Failed nodes deployment in host : localhost/127.0.0.1, retries left : 0
[2018-09-12 16:44:48,524 -thread-17 ERROR FileBasedInfrastructureManager] Tries threshold reached for host localhost/127.0.0.1. This host is not part of the deployment process anymore.
[2018-09-12 16:44:48,525 -thread-17 ERROR FileBasedInfrastructureManager] Could not acquire nodes on host Host localhost. Configured with 2 nodes. Current state: [alive node number=0, down node number=0, remove$
 node number=0].
org.ow2.proactive.resourcemanager.exception.RMException: unable to deploy on localhost/127.0.0.1
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2.startNodeImpl(SSHInfrastructureV2.java:249)
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.HostsFileBasedInfrastructureManager.startNodeImplWithRetries(HostsFileBasedInfrastructureManager.java:307)
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.HostsFileBasedInfrastructureManager$1.run(HostsFileBasedInfrastructureManager.java:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2.startNodeImpl(SSHInfrastructureV2.java:246)
        ... 5 more
[2018-09-12 16:44:54,493 ner Thread INFO         o.o.p.c.SessionsCleaner] cleaning session started, 1 existing session(s)
[2018-09-12 16:44:54,494 ner Thread INFO         o.o.p.c.SessionsCleaner] cleaning session ended, 0 session(s) removed
[2018-09-12 16:44:56,555 "cccccccc" INFO            o.o.p.r.n.NodeSource] [cccccccc] Pinging alive nodes: 0
[2018-09-12 16:45:20,718  "aaaaaaa" INFO            o.o.p.r.n.NodeSource] [aaaaaaa] Pinging alive nodes : 0
[2018-09-12 16:45:21,349 alInfrass" INFO            o.o.p.r.n.NodeSource] [MyLocalInfrass] Pinging alivenodes : 0
[2018-09-12 16:45:41,556 "cccccccc" INFO            o.o.p.r.n.NodeSource] [cccccccc] Pinging alive nodes: 0
[2018-09-12 16:46:05,719  "aaaaaaa" INFO            o.o.p.r.n.NodeSource] [aaaaaaa] Pinging alive nodes : 0
[2018-09-12 16:46:06,430 ySSHInfra" INFO            o.o.p.r.n.NodeSource] [MySSHInfra] Pinging alive nodes : 0
[2018-09-12 16:46:11,570 ocalNodes" INFO            o.o.p.r.n.NodeSource] [LocalNodes] Pinging alive nodes : 7
[2018-09-12 16:46:51,349 alInfrass" INFO            o.o.p.r.n.NodeSource] [MyLocalInfrass] Pinging alivenodes : 0
[2018-09-12 16:47:11,556 "cccccccc" INFO            o.o.p.r.n.NodeSource] [cccccccc] Pinging alive nodes: 0
[2018-09-12 16:47:35,719  "aaaaaaa" INFO            o.o.p.r.n.NodeSource] [aaaaaaa] Pinging alive nodes : 0
[2018-09-12 16:47:36,350 alInfrass" INFO            o.o.p.r.n.NodeSource] [MyLocalInfrass] Pinging alivenodes : 0
[2018-09-12 16:47:36,430 ySSHInfra" INFO            o.o.p.r.n.NodeSource] [MySSHInfra] Pinging alive nodes : 0
[2018-09-12 16:47:41,571 ocalNodes" INFO            o.o.p.r.n.NodeSource] [LocalNodes] Pinging alive nodes : 7
[2018-09-12 16:47:56,557 "cccccccc" INFO            o.o.p.r.n.NodeSource] [cccccccc] Pinging alive nodes: 0
[2018-09-12 16:48:17,461 38/RM_NODE INFO                o.o.p.r.c.RMCore] Update dynamic parameters of node source cccccccc requested by admin
[2018-09-12 16:48:17,466 38/RM_NODE INFO                o.o.p.r.c.RMCore] Node source cccccccc has been successfully updated with dynamic parameters
[2018-09-12 16:48:20,720  "aaaaaaa" INFO            o.o.p.r.n.NodeSource] [aaaaaaa] Pinging alive nodes : 0
[2018-09-12 16:48:21,431 ySSHInfra" INFO            o.o.p.r.n.NodeSource] [MySSHInfra] Pinging alive nodes : 0
[2018-09-12 16:48:22,479 atus check INFO  p.r.n.p.RestartDownNodesPolicy] Removing lost node deploying://cccccccc/cccccccc__localhost__22_0
[2018-09-12 16:48:22,487 atus check INFO  p.r.n.p.RestartDownNodesPolicy] Lost node removed
[2018-09-12 16:48:22,487 atus check INFO  p.r.n.p.RestartDownNodesPolicy] Removing lost node deploying://cccccccc/cccccccc__localhost__22_1
[2018-09-12 16:48:22,494 atus check INFO  p.r.n.p.RestartDownNodesPolicy] Lost node removed
[2018-09-12 16:48:22,494 atus check INFO  p.r.n.p.RestartDownNodesPolicy] Acquiring 2 nodes
[2018-09-12 16:48:22,494 atus check INFO    o.o.p.r.n.p.NodeSourcePolicy] [cccccccc] Acquiring 2 nodes
[2018-09-12 16:48:22,494 "cccccccc" INFO  FileBasedInfrastructureManager] Attempting to acquire nodes while nodes are already deployed on all hosts.
[2018-09-12 16:48:22,494 "cccccccc" INFO  FileBasedInfrastructureManager] Attempting to acquire nodes while nodes are already deployed on all hosts.
[2018-09-12 16:49:06,350 alInfrass" INFO            o.o.p.r.n.NodeSource] [MyLocalInfrass] Pinging alivenodes : 0
[2018-09-12 16:49:07,495 "cccccccc" INFO            o.o.p.r.n.NodeSource] [cccccccc] Pinging alive nodes: 0`

**Comment by fviale** [comment]
fixed by fbd70eb668bf807357e9a13e09bee258a384aa18
