### ISSUE TITLE
NPE during HOUSEKEEPING

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#3477]
The following error appears during housekeeping, preventing its execution:

```
[2019-02-13 20:20:10,137 57388929b] ERROR    o.o.p.s.c.SchedulingService] Error performing HOUSEKEEPING of jobs
java.lang.NullPointerException
	at org.ow2.proactive.scheduler.core.SchedulerFrontendState.jobStateUpdated(SchedulerFrontendState.java:1113)
	at org.ow2.proactive.scheduler.core.SchedulingService$HousekeepingRunner.removeFromContext(SchedulingService.java:1090)
	at org.ow2.proactive.scheduler.core.SchedulingService$HousekeepingRunner.run(SchedulingService.java:1120)
	at it.sauronsoftware.cron4j.RunnableTask.execute(Unknown Source)
	at it.sauronsoftware.cron4j.TaskExecutor$Runner.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by fviale** [comment]
fixed by associated commits
