### ISSUE TITLE
SchedulerDBManager.getTaskStates throws exception because of invalid query field

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#3502]
The issue can be reproduced using the scheduler portal, task centric view, and filtering by Tag

The following exception appears in the log:
```
[2019-03-07 12:24:18,804 de45983347 WARN       o.o.p.d.TransactionHelper] Database operation failed. Automatic retry in 32000 ms (attempt 5)
org.hibernate.QueryException: could not resolve property: jobId of: org.ow2.proactive.scheduler.core.db.TaskData [select T from org.ow2.proactive.scheduler.core.db.TaskData T where T.jobData.removedTime = -1 and ( ( startTime >= :dateFrom and startTime <= :dateTo ) or ( scheduledTime >= :dateFrom and scheduledTime <= :dateTo ) or ( finishedTime >= :dateFrom and finishedTime <= :dateTo ) ) and tag = :taskTag and taskStatus in (:taskStatus) order by T.jobId DESC ]
        at org.hibernate.QueryException.generateQueryException(QueryException.java:120)
        at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:218)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:142)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:76)
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:150)
        at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:302)
        at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:240)
        at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1907)
        at org.ow2.proactive.scheduler.core.db.TaskDBUtils.getQuery(TaskDBUtils.java:133)
        at org.ow2.proactive.scheduler.core.db.TaskDBUtils.fetchTaskData(TaskDBUtils.java:113)
        at org.ow2.proactive.scheduler.core.db.TaskDBUtils.lambda$taskStateSessionWork$1(TaskDBUtils.java:84)
        at org.ow2.proactive.db.TransactionHelper.tryExecuteTransaction(TransactionHelper.java:135)
        at org.ow2.proactive.db.TransactionHelper.tryExecuteTransactionLoop(TransactionHelper.java:99)
        at org.ow2.proactive.db.TransactionHelper.executeReadOnlyTransaction(TransactionHelper.java:63)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.executeReadOnlyTransaction(SchedulerDBManager.java:1727)
        at org.ow2.proactive.scheduler.core.db.SchedulerDBManager.getTaskStates(SchedulerDBManager.java:298)
        at org.ow2.proactive.scheduler.core.SchedulerFrontend.getTaskStates(SchedulerFrontend.java:1464)
        at sun.reflect.GeneratedMethodAccessor1445.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
        at org.objectweb.proactive.core.body.request.RequestReceiverImpl.receiveRequest(RequestReceiverImpl.java:161)
        at org.objectweb.proactive.core.body.BodyImpl.internalReceiveRequest(BodyImpl.java:210)
        at org.objectweb.proactive.core.body.AbstractBody.receiveRequest(AbstractBody.java:221)
        at org.objectweb.proactive.core.body.request.RequestImpl.sendRequest(RequestImpl.java:229)
        at org.objectweb.proactive.core.body.request.RequestImpl.send(RequestImpl.java:140)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.sendRequest(BodyImpl.java:742)
        at org.objectweb.proactive.core.body.AbstractBody.sendRequest(AbstractBody.java:436)
        at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequestInternal(UniversalBodyProxy.java:436)
        at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:410)
        at org.objectweb.proactive.core.body.proxy.UniversalBodyProxy.sendRequest(UniversalBodyProxy.java:339)
        at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reifyAsSynchronous(AbstractBodyProxy.java:320)
        at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.invokeOnBody(AbstractBodyProxy.java:159)
        at org.objectweb.proactive.core.body.proxy.AbstractBodyProxy.reify(AbstractBodyProxy.java:113)
        at pa.stub.org.ow2.proactive.scheduler.common._StubScheduler.getTaskStates(_StubScheduler.java)
        at org.ow2.proactive.scheduler.common.util.SchedulerProxyUserInterface.getTaskStates(SchedulerProxyUserInterface.java:650)
        at sun.reflect.GeneratedMethodAccessor1444.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
        at org.objectweb.proactive.Service.serve(Service.java:119)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:178)
        at org.objectweb.proactive.Service.fifoServing(Service.java:141)
        at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:329)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.QueryException: could not resolve property: jobId of: org.ow2.proactive.scheduler.core.db.TaskData
        at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:62)
        at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:56)
        at org.hibernate.persister.entity.AbstractEntityPersister.toType(AbstractEntityPersister.java:1788)
        at org.hibernate.hql.internal.ast.tree.FromElementType.getPropertyType(FromElementType.java:393)
        at org.hibernate.hql.internal.ast.tree.FromElement.getPropertyType(FromElement.java:505)
        at org.hibernate.hql.internal.ast.tree.DotNode.getDataType(DotNode.java:660)
        at org.hibernate.hql.internal.ast.tree.DotNode.prepareLhs(DotNode.java:264)
        at org.hibernate.hql.internal.ast.tree.DotNode.resolve(DotNode.java:204)
        at org.hibernate.hql.internal.ast.tree.FromReferenceNode.resolve(FromReferenceNode.java:109)
        at org.hibernate.hql.internal.ast.tree.FromReferenceNode.resolve(FromReferenceNode.java:104)
        at org.hibernate.hql.internal.ast.HqlSqlWalker.resolve(HqlSqlWalker.java:1013)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.expr(HqlSqlBaseWalker.java:1286)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.orderExpr(HqlSqlBaseWalker.java:1856)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.orderExprs(HqlSqlBaseWalker.java:1653)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.orderClause(HqlSqlBaseWalker.java:1626)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:652)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:311)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:259)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:262)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:190)
        ... 56 more
```

**Comment by mbenguig** [comment]
Not able to reproduce it. Can be closed.
